// Pass 3: final enrichment to push all lessons above 4000 words
// Adds ~1500-2000 words of NEW content per topic (different from pass 1 & 2)
const SUPABASE_URL = 'https://xkecqmsgvjjtujvlotpm.supabase.co';
const SK = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZWNxbXNndmpqdHVqdmxvdHBtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjU4NDIxNSwiZXhwIjoyMDgyMTYwMjE1fQ.jOOgWSgXTqOKtr1fFqh4RIhwXzd7ZcF9XjOihpCHCnU';
const H = { 'apikey': SK, 'Authorization': `Bearer ${SK}`, 'Content-Type': 'application/json' };

async function fetchAll() {
  let all = [], offset = 0;
  while (true) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/lessons?select=id,title,content,course_id&limit=100&offset=${offset}`, { headers: H });
    const data = await res.json();
    if (!data.length) break;
    all = all.concat(data);
    offset += 100;
  }
  return all;
}

async function update(id, content) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/lessons?id=eq.${id}`, {
    method: 'PATCH', headers: { ...H, 'Prefer': 'return=minimal' },
    body: JSON.stringify({ content })
  });
  return res.status;
}

function getTopic(title, courseTitle) {
  const t = (title + ' ' + (courseTitle||'')).toLowerCase();
  if (t.includes('logement') || t.includes('bail') || t.includes('locat') || t.includes('caution') || t.includes('préavis') || t.includes('demenag') || t.includes('déménag') || t.includes('état des lieux') || t.includes('garant') || t.includes('visale') || t.includes('copropri') || t.includes('annonce') || t.includes('meublé') || t.includes('colocation') || t.includes('énergie') || t.includes('compteur') || t.includes('assurance habitation') || t.includes('internet') || t.includes('fibre')) return 'logement';
  if (t.includes('banqu') || t.includes('bancaire') || t.includes('rib') || t.includes('chequ') || t.includes('frais') || t.includes('agios') || t.includes('clôturer') || t.includes('carte bancaire') || t.includes('virement') || t.includes('compte')) return 'banque';
  if (t.includes('transport') || t.includes('navigo') || t.includes('velib') || t.includes('vélib') || t.includes('sncf') || t.includes('train') || t.includes('voyag') || t.includes('trottinette') || t.includes('metro') || t.includes('bus')) return 'transport';
  if (t.includes('cv') || t.includes('emploi') || t.includes('travail') || t.includes('job') || t.includes('lettre') || t.includes('motivation') || t.includes('alternance') || t.includes('stage') || t.includes('statut') || t.includes('salari') || t.includes('linkedin') || t.includes('network') || t.includes('alumni') || t.includes('entretien') || t.includes('candidat') || t.includes('auto-entrepreneur') || t.includes('pôle emploi') || t.includes('télétravail') || t.includes('législation')) return 'emploi';
  if (t.includes('santé') || t.includes('sante') || t.includes('carte vitale') || t.includes('médecin') || t.includes('medecin') || t.includes('cpam') || t.includes('sécu') || t.includes('mutuelle') || t.includes('rembours') || t.includes('pharma') || t.includes('doctolib') || t.includes('lunettes') || t.includes('dents') || t.includes('sexuel') || t.includes('psycho') || t.includes('ofii') || t.includes('soins') || t.includes('ifsi')) return 'sante';
  if (t.includes('préfecture') || t.includes('titre') || t.includes('visa') || t.includes('vls') || t.includes('anef') || t.includes('campus france') || t.includes('renouvellement') || t.includes('identit') || t.includes('légalisation') || t.includes('permis') || t.includes('service-public') || t.includes('aps') || t.includes('région') || t.includes('checklist') || t.includes('départ')) return 'administratif';
  if (t.includes('français') || t.includes('francais') || t.includes('delf') || t.includes('dalf') || t.includes('b1') || t.includes('b2') || t.includes('a1') || t.includes('grammaire') || t.includes('prononciation')) return 'francais';
  if (t.includes('impôt') || t.includes('impot') || t.includes('fiscal') || t.includes('taxe') || t.includes('avis') || t.includes('teom')) return 'fiscal';
  if (t.includes('caf') || t.includes('apl') || t.includes('aide') || t.includes('bourse')) return 'aides';
  if (t.includes('universi') || t.includes('examen') || t.includes('inscription') || t.includes('campus') || t.includes('études')) return 'universite';
  if (t.includes('urgence') || t.includes('secours') || t.includes('sécurité') || t.includes('pickpocket') || t.includes('objets')) return 'securite';
  if (t.includes('bise') || t.includes('tu ou vous') || t.includes('politesse') || t.includes('apéro') || t.includes('café') || t.includes('boulangerie') || t.includes('pourboire') || t.includes('cinéma') || t.includes('grève') || t.includes('férié') || t.includes('association') || t.includes('amis') || t.includes('lgbtq') || t.includes('tabac') || t.includes('alcool') || t.includes('laïcité') || t.includes('codes sociaux') || t.includes('pass culture') || t.includes('resto') || t.includes('repas') || t.includes('coiffeur') || t.includes('animaux') || t.includes('laver') || t.includes('laverie') || t.includes('poste') || t.includes('occasion') || t.includes('tri') || t.includes('budget') || t.includes('manger') || t.includes('courses') || t.includes('forfait') || t.includes('mobile')) return 'culture';
  return 'pratique';
}

const pass3Blocks = {

logement: `
<h3>Les diagnostics immobiliers obligatoires et la protection du locataire</h3>
<p>Avant toute mise en location en France, le propriétaire est légalement tenu de fournir un <strong>Dossier de Diagnostic Technique (DDT)</strong> comprenant plusieurs diagnostics obligatoires. Le <strong>Diagnostic de Performance Énergétique (DPE)</strong> classe le logement de A (excellent) à G (passoire thermique) et renseigne sur la consommation énergétique estimée. Depuis le 1er janvier 2025, les logements classés G sont interdits à la location, et cette interdiction s'étendra aux logements classés F en 2028 puis E en 2034. Le <strong>diagnostic plomb (CREP)</strong> est obligatoire pour les logements construits avant le 1er janvier 1949 et permet de détecter les risques d'exposition au plomb dans les peintures. Le <strong>diagnostic amiante</strong> concerne les immeubles dont le permis de construire a été délivré avant le 1er juillet 1997. L'<strong>état des risques et pollutions (ERP)</strong> informe le locataire sur les risques naturels (inondation, séisme), technologiques et miniers auxquels est exposé le logement. Le <strong>diagnostic électricité et gaz</strong> est obligatoire lorsque l'installation a plus de 15 ans et doit être renouvelé tous les 6 ans.</p>

<p>En tant que locataire en France, vous bénéficiez de protections juridiques solides. La <strong>loi du 6 juillet 1989</strong> encadre les rapports locatifs et protège le locataire contre les abus : le propriétaire ne peut pas entrer dans le logement sans votre accord, ne peut pas couper l'eau ou l'électricité, et ne peut pas vous expulser sans décision de justice (la trêve hivernale du 1er novembre au 31 mars interdit toute expulsion). Le <strong>décret décence</strong> impose que le logement loué respecte des critères minimaux : surface habitable d'au moins 9 m2 avec une hauteur sous plafond de 2,20 m minimum, installation de chauffage, alimentation en eau potable, évacuation des eaux usées, et absence de risques manifestes pour la santé. Si le logement ne respecte pas ces critères, le locataire peut saisir la <strong>Commission départementale de conciliation (CDC)</strong> ou le tribunal judiciaire pour obtenir la mise en conformité ou une réduction de loyer. L'<a href="https://www.anil.org" target="_blank">ANIL (Agence Nationale d'Information sur le Logement)</a> dispose d'antennes dans tous les départements (ADIL) qui offrent des consultations juridiques gratuites sur toutes les questions de logement.</p>

<h3>Gérer les litiges et les problèmes courants en location</h3>
<p>Les problèmes les plus fréquents rencontrés par les étudiants internationaux en location en France concernent la <strong>restitution du dépôt de garantie</strong>, les <strong>charges locatives</strong> et les <strong>troubles de voisinage</strong>. Pour le dépôt de garantie, le propriétaire dispose d'un délai maximal d'un mois (si l'état des lieux de sortie est conforme à l'entrée) ou deux mois (en cas de différences) pour le restituer. Au-delà de ce délai, le locataire peut facturer une pénalité de 10% du loyer mensuel par mois de retard. Conservez précieusement votre état des lieux d'entrée et prenez des photos horodatées le jour de votre emménagement. Pour les charges locatives, le propriétaire doit vous fournir une régularisation annuelle détaillée. En cas de trop-perçu, il doit vous rembourser la différence. Pour les troubles de voisinage (bruit excessif, nuisances), le premier réflexe est la médiation amiable. Si cela échoue, vous pouvez saisir le conciliateur de justice (service gratuit) ou le tribunal de proximité. Le numéro <strong>0 806 000 113</strong> (service SOS Loyers Impayés) peut aider en cas de difficultés de paiement du loyer. L'association <a href="https://www.clcv.org" target="_blank">CLCV</a> et la <a href="https://www.quechoisir.org" target="_blank">UFC-Que Choisir</a> proposent un accompagnement gratuit pour les litiges de consommation liés au logement.</p>`,

banque: `
<h3>Les néobanques et banques en ligne : alternatives modernes pour les étudiants</h3>
<p>Au-delà des banques traditionnelles, les étudiants internationaux en France ont accès à un écosystème riche de <strong>néobanques et banques en ligne</strong> qui offrent souvent des services plus adaptés à leurs besoins. <a href="https://www.boursobank.com" target="_blank">BoursoBank</a> (anciennement Boursorama) propose un compte courant 100% gratuit sans condition de revenus, une carte Visa sans frais, et des paiements sans commission dans toutes les devises. <a href="https://www.fortuneo.fr" target="_blank">Fortuneo</a> offre un positionnement similaire avec une carte Gold MasterCard gratuite sous condition d'un revenu mensuel de 1 200 euros ou d'un encours de 5 000 euros. Pour les plus petits budgets, <a href="https://n26.com/fr-fr" target="_blank">N26</a> propose un compte basique gratuit avec une carte virtuelle et des notifications en temps réel de chaque transaction. <a href="https://www.revolut.com/fr-FR" target="_blank">Revolut</a> est particulièrement apprécié des étudiants internationaux pour ses transferts internationaux à taux réel sans majoration jusqu'à 1 000 euros par mois en version gratuite. <a href="https://www.lydia-app.com" target="_blank">Lydia</a>, l'application française de paiement mobile, est devenue incontournable chez les étudiants français pour envoyer et recevoir de l'argent instantanément entre amis.</p>

<p>Pour ouvrir un compte bancaire en France en tant qu'étudiant international, vous aurez besoin de : un <strong>passeport ou carte d'identité</strong> valide, un <strong>justificatif de domicile</strong> (quittance de loyer, attestation d'hébergement, ou facture d'électricité/internet à votre nom), et un <strong>certificat de scolarité</strong> ou attestation d'inscription dans un établissement français. Si vous n'avez pas encore de justificatif de domicile français, certaines banques en ligne acceptent une attestation d'hébergement temporaire ou un contrat de location non encore effectif. Le <strong>droit au compte</strong> garanti par la loi française (article L312-1 du Code monétaire et financier) vous protège : si trois banques vous refusent l'ouverture d'un compte, vous pouvez saisir la Banque de France qui désignera d'office un établissement tenu de vous ouvrir un compte avec les services bancaires de base. Ce droit s'applique à toute personne résidant en France, quelle que soit sa nationalité.</p>

<h3>Comprendre et optimiser ses frais bancaires</h3>
<p>Les frais bancaires constituent un poste de dépense souvent sous-estimé par les étudiants internationaux. Les <strong>frais de tenue de compte</strong> varient de 0 euros (banques en ligne) à 30 euros par an (banques traditionnelles). Les <strong>commissions d'intervention</strong> sont plafonnées à 8 euros par opération et 80 euros par mois pour les comptes standards, et à 4 euros par opération et 20 euros par mois pour les clients en situation de fragilité financière. Les <strong>virements internationaux SEPA</strong> (zone euro) sont gratuits et aussi rapides qu'un virement national. Les virements hors SEPA coûtent entre 5 et 25 euros par virement en banque traditionnelle. Privilégiez <a href="https://wise.com/fr/" target="_blank">Wise</a> ou <a href="https://www.revolut.com" target="_blank">Revolut</a> pour des transferts internationaux à moindre coût. Les <strong>retraits dans les distributeurs</strong> d'une autre banque sont généralement gratuits pour les 3-4 premiers par mois, puis facturés environ 1 euro par retrait. Le <strong>paiement sans contact</strong> est omniprésent en France (plafond de 50 euros par transaction) et fonctionne avec votre carte bancaire, votre téléphone ou votre montre connectée. Pour réduire vos frais, activez les alertes push pour surveiller votre solde en temps réel.</p>`,

transport: `
<h3>Les abonnements de transport en commun dans les grandes villes françaises</h3>
<p>Chaque grande agglomération française dispose de son propre réseau de transport en commun avec un système tarifaire spécifique. En <strong>Ile-de-France</strong>, le <a href="https://www.iledefrance-mobilites.fr" target="_blank">pass Navigo</a> donne accès à l'ensemble du réseau (métro, RER, bus, tramway) dans toutes les zones sans restriction. Les étudiants de moins de 26 ans bénéficient du tarif réduit <strong>Imagine R</strong> qui représente un avantage considérable. A <strong>Lyon</strong>, le réseau <a href="https://www.tcl.fr" target="_blank">TCL</a> propose un abonnement étudiant avantageux. A <strong>Toulouse</strong>, le réseau <a href="https://www.tisseo.fr" target="_blank">Tisséo</a> offre l'un des abonnements jeune/étudiant les moins chers de France. A <strong>Bordeaux</strong>, le réseau <a href="https://www.infotbm.com" target="_blank">TBM</a> propose un abonnement étudiant compétitif. A <strong>Marseille</strong>, le réseau <a href="https://www.rtm.fr" target="_blank">RTM</a> offre un tarif étudiant abordable. A <strong>Strasbourg</strong>, le <a href="https://www.cts-strasbourg.eu" target="_blank">CTS</a> propose un abonnement campus intéressant. Renseignez-vous auprès du réseau de transport de votre ville dès votre arrivée pour obtenir votre abonnement étudiant.</p>

<p>Pour les <strong>déplacements interurbains</strong>, les étudiants disposent de plusieurs options économiques. Les <strong>cars régionaux</strong> (FlixBus, BlaBlaCar Bus) proposent des trajets entre grandes villes à des tarifs très compétitifs. Le <a href="https://www.blablacar.fr" target="_blank">covoiturage BlaBlaCar</a> permet de partager les frais d'un trajet en voiture avec d'autres passagers. Pour le <strong>train</strong>, la carte <a href="https://www.sncf-connect.com/app/catalogue/description/carte-avantage-jeune" target="_blank">Avantage Jeune SNCF</a> (pour les 12-27 ans) offre 30% de réduction garantie sur tous les TGV et Intercités, et jusqu'à 60% de réduction en réservant à l'avance. Les trains <strong>Ouigo</strong> (TGV low-cost de la SNCF) proposent des billets abordables vers de nombreuses destinations. Pour les voyages en Europe, les <strong>trains de nuit</strong> font leur retour avec les liaisons Paris-Nice, Paris-Toulouse, et bientôt Paris-Berlin. Le <a href="https://www.interrail.eu/fr" target="_blank">pass Interrail</a> permet de voyager en train dans 33 pays européens avec des réductions significatives pour les moins de 27 ans.</p>

<h3>Le vélo et les mobilités douces : se déplacer au quotidien</h3>
<p>Les villes françaises investissent massivement dans les <strong>infrastructures cyclables</strong>. Paris compte désormais plus de 1 000 km de pistes cyclables, et le plan vélo prévoit d'atteindre 180 km de pistes protégées (REVe). Le <a href="https://www.velib-metropole.fr" target="_blank">Vélib'</a> parisien propose un abonnement étudiant intéressant avec des trajets inclus. Lyon dispose de <a href="https://velov.grandlyon.com" target="_blank">Vélo'v</a>, Toulouse du <a href="https://www.velo.toulouse.fr" target="_blank">VélôToulouse</a>, Bordeaux des <a href="https://www.vcub.fr" target="_blank">VCub</a>. Pour acheter un vélo d'occasion, consultez <a href="https://www.leboncoin.fr" target="_blank">Leboncoin</a>, les bourses aux vélos organisées par les associations locales, ou les ateliers vélo participatifs (type <a href="https://www.heureux-cyclage.org" target="_blank">L'Heureux Cyclage</a>) où vous pouvez apprendre à réparer et entretenir votre vélo vous-même pour quelques euros. L'<strong>aide à l'achat d'un vélo</strong> de l'Etat peut atteindre 400 euros pour un vélo électrique, avec des aides complémentaires de la ville et de la région. Pensez à immatriculer votre vélo via le dispositif <a href="https://www.bicycode.org" target="_blank">Bicycode</a> pour réduire le risque de vol et faciliter la restitution en cas de vol retrouvé par la police.</p>`,

emploi: `
<h3>Les droits fondamentaux du salarié en France</h3>
<p>Le droit du travail français est l'un des plus protecteurs au monde pour les salariés. En tant qu'étudiant international travaillant en France, vous bénéficiez exactement des mêmes droits que les travailleurs français. Le <strong>SMIC (Salaire Minimum Interprofessionnel de Croissance)</strong> est revalorisé chaque année et constitue le salaire horaire minimum légal. Votre salaire net sera environ 22% inférieur au brut après cotisations sociales. Le <strong>temps de travail légal</strong> est de 35 heures par semaine ; au-delà, les heures sont considérées comme des heures supplémentaires et majorées : +25% pour les 8 premières heures supplémentaires, puis +50% au-delà. Chaque salarié a droit à un minimum de <strong>5 semaines de congés payés</strong> par an. En tant qu'étudiant avec un titre de séjour étudiant, vous êtes autorisé à travailler <strong>964 heures par an</strong> (soit environ 60% de la durée annuelle légale de travail). Ce quota est calculé sur la période de validité de votre titre de séjour.</p>

<p>La <strong>fiche de paie</strong> française est un document détaillé qui mentionne : le salaire brut, les cotisations salariales (maladie, chômage, retraite, CSG, CRDS), le salaire net imposable, le salaire net à payer, et les informations sur l'employeur et le salarié. Depuis le 1er janvier 2019, le <strong>prélèvement à la source</strong> de l'impôt sur le revenu est directement effectué sur votre fiche de paie. Conservez toutes vos fiches de paie pendant toute votre vie car elles servent de preuve pour le calcul de votre retraite et peuvent être demandées lors de démarches administratives. En cas de licenciement, le <strong>préavis</strong> dépend de votre ancienneté. Le licenciement doit être justifié par une cause réelle et sérieuse ; à défaut, le salarié peut contester devant le <strong>Conseil de prud'hommes</strong>, la juridiction spécialisée en droit du travail. L'inscription à <a href="https://www.francetravail.fr" target="_blank">France Travail</a> (ex-Pôle Emploi) après la fin d'un contrat ouvre droit aux allocations chômage si vous avez travaillé au moins 6 mois sur les 24 derniers mois.</p>

<h3>Trouver un job étudiant ou un stage en France</h3>
<p>Les meilleures plateformes pour trouver un job étudiant en France sont : <a href="https://www.indeed.fr" target="_blank">Indeed</a> (la plus utilisée en France), <a href="https://www.studentjob.fr" target="_blank">StudentJob</a> (spécialisé emplois étudiants), <a href="https://www.jobteaser.com" target="_blank">JobTeaser</a> (partenaire de nombreuses universités), <a href="https://www.welcometothejungle.com" target="_blank">Welcome to the Jungle</a> (startups et tech), et le site de votre université qui publie souvent des offres en interne. Les secteurs qui recrutent le plus d'étudiants sont la <strong>restauration</strong>, la <strong>grande distribution</strong>, le <strong>baby-sitting et soutien scolaire</strong>, et le <strong>tutorat linguistique</strong> (un atout considérable pour les étudiants internationaux maîtrisant l'anglais, l'espagnol, le chinois ou l'arabe). Pour les stages, la convention de stage est obligatoire et doit être signée par l'étudiant, l'entreprise et l'établissement d'enseignement. Un stage de plus de 2 mois consécutifs ouvre droit à une <strong>gratification minimale</strong>. Les <a href="https://www.service-civique.gouv.fr" target="_blank">missions de service civique</a> constituent une excellente alternative : elles sont accessibles aux 16-25 ans de toutes nationalités, indemnisées environ 600 euros par mois, et offrent une expérience valorisante en association ou service public.</p>`,

sante: `
<h3>Le parcours de soins coordonné et le médecin traitant</h3>
<p>Le système de santé français repose sur le <strong>parcours de soins coordonné</strong>, qui implique de déclarer un <strong>médecin traitant</strong> auprès de la Sécurité sociale. Ce médecin est votre premier interlocuteur pour tout problème de santé non urgent. Il vous oriente si nécessaire vers des spécialistes. Sans médecin traitant, ou en consultant un spécialiste directement (hors ophtalmologue, gynécologue, psychiatre et dentiste), le taux de remboursement est réduit de 40%. Pour déclarer un médecin traitant, remplissez le formulaire <strong>Cerfa n12485</strong> directement chez le médecin choisi, qui transmettra la déclaration à la CPAM. Tout médecin généraliste peut être choisi, et vous pouvez en changer à tout moment. Pour trouver un médecin traitant qui accepte de nouveaux patients, utilisez <a href="https://www.doctolib.fr" target="_blank">Doctolib</a>, <a href="https://www.maiia.com" target="_blank">Maiia</a>, ou appelez le <strong>3646</strong> (CPAM) qui dispose d'un service d'aide à la recherche de médecin traitant.</p>

<p>En cas d'urgence, plusieurs dispositifs existent en France. Le <strong>15 (SAMU)</strong> est le numéro d'urgence médicale disponible 24h/24 : un médecin régulateur évalue votre situation et oriente vers la réponse adaptée. Le <strong>112</strong> est le numéro d'urgence européen, accessible dans toute l'UE. Les <strong>services d'urgence hospitaliers</strong> sont accessibles à tous, 24h/24, sans rendez-vous et sans avance de frais pour les détenteurs de la carte Vitale. Cependant, les temps d'attente peuvent être très longs pour les cas non vitaux. Pour les urgences mineures le soir et le week-end, les <strong>maisons médicales de garde</strong> accueillent sans rendez-vous et évitent l'engorgement des urgences hospitalières. La <strong>téléconsultation</strong> s'est considérablement développée : des plateformes comme <a href="https://www.qare.fr" target="_blank">Qare</a>, <a href="https://www.livi.fr" target="_blank">Livi</a> et <a href="https://www.medadom.com" target="_blank">Medadom</a> permettent de consulter un médecin en vidéo, remboursé par la Sécurité sociale. La pharmacie de garde est accessible la nuit et les dimanches/jours fériés. Appelez le <strong>3237</strong> ou consultez le site <a href="https://www.3237.fr" target="_blank">3237.fr</a> pour trouver la pharmacie de garde la plus proche.</p>

<h3>La santé mentale : ressources et accompagnement</h3>
<p>La santé mentale des étudiants est une priorité en France. Les <strong>Services de Santé Etudiante (SSE)</strong> de chaque université proposent des consultations psychologiques gratuites avec des psychologues cliniciens. Le dispositif national <strong>MonPsy</strong> permet à tout étudiant de bénéficier de 8 séances chez un psychologue conventionné remboursées par la Sécurité sociale (sur adressage du médecin traitant). Les <strong>Bureaux d'Aide Psychologique Universitaire (BAPU)</strong> offrent des consultations gratuites et sans avance de frais aux étudiants, avec des psychologues et des psychiatres. En cas de crise, le <strong>3114</strong> est le numéro national de prévention du suicide, disponible 24h/24 et 7j/7, gratuit et confidentiel. <a href="https://www.nightline.fr" target="_blank">Nightline</a> est un service d'écoute nocturne tenu par des étudiants bénévoles formés, disponible dans de nombreuses villes universitaires. L'association <a href="https://www.filsantejeunes.com" target="_blank">Fil Santé Jeunes</a> propose un chat en ligne et un numéro gratuit (0 800 235 236) pour les 12-25 ans.</p>`,

administratif: `
<h3>Le système administratif français : comprendre la bureaucratie</h3>
<p>L'administration française est réputée pour sa complexité, mais elle s'est considérablement modernisée ces dernières années grâce à la dématérialisation. Le portail <a href="https://www.service-public.fr" target="_blank">service-public.fr</a> est la porte d'entrée unique vers toutes les démarches administratives en ligne : création de compte, suivi de dossiers, téléchargement de formulaires. <a href="https://www.franceconnect.gouv.fr" target="_blank">FranceConnect</a> est un système d'authentification unique qui permet d'accéder à des centaines de services publics en ligne (impôts, CPAM, CAF, ANTS, etc.) avec un seul identifiant. Pour créer votre compte FranceConnect, vous pouvez utiliser vos identifiants d'Ameli.fr, des impôts, ou de La Poste. Le portail <a href="https://administration-etrangers-en-france.interieur.gouv.fr" target="_blank">ANEF</a> (Administration Numérique des Etrangers en France) centralise toutes les démarches liées au séjour : demande et renouvellement de titre de séjour, changement de statut, demande d'autorisation provisoire de séjour (APS). La plupart des démarches en préfecture nécessitent désormais un <strong>rendez-vous en ligne</strong>.</p>

<p>Les <strong>délais administratifs</strong> en France peuvent être longs et il est crucial de les anticiper. Le renouvellement du titre de séjour doit être demandé <strong>2 à 4 mois avant l'expiration</strong> du titre en cours. La première carte Vitale prend en moyenne 4 à 6 semaines après la demande. L'admission à l'aide au logement (APL) prend environ 1 à 2 mois après le dépôt du dossier complet. Pour toute démarche administrative, préparez systématiquement : une <strong>copie de votre passeport</strong> (pages d'identité + visa + tampons d'entrée), votre <strong>titre de séjour</strong> (ou récépissé), un <strong>justificatif de domicile de moins de 3 mois</strong>, une <strong>photo d'identité aux normes françaises</strong> (format 35x45mm, fond clair uni, visage dégagé), et un <strong>RIB</strong>. La <a href="https://www.legifrance.gouv.fr" target="_blank">Légifrance</a> est le site officiel de publication des textes juridiques français. Pour les traductions assermentées de documents officiels (diplômes, actes de naissance), consultez la liste des traducteurs agréés sur le site de la <a href="https://www.cours-appel.justice.fr" target="_blank">Cour d'appel</a> de votre juridiction.</p>

<h3>Les consulats et les relations avec votre pays d'origine</h3>
<p>Une fois installé en France, il est recommandé de vous inscrire au registre consulaire de votre ambassade/consulat. Cette inscription facilite les démarches consulaires (renouvellement de passeport, vote, aide en cas d'urgence) et permet à votre pays d'origine de vous contacter en cas de crise (catastrophe naturelle, trouble politique, pandémie). La plupart des ambassades proposent désormais une inscription en ligne. Les <strong>documents français nécessitant une apostille</strong> pour être valides dans votre pays d'origine doivent être apostillés auprès de la Cour d'appel du lieu de résidence. La procédure est gratuite et prend environ 1 à 3 semaines. Pour les pays non signataires de la Convention de La Haye, une <strong>légalisation consulaire</strong> est nécessaire auprès du Ministère des Affaires Etrangères puis du consulat de votre pays en France.</p>`,

francais: `
<h3>Progresser en français au quotidien : méthodes et ressources</h3>
<p>L'apprentissage du français ne se limite pas aux cours formels. Les étudiants internationaux qui progressent le plus rapidement sont ceux qui combinent l'étude structurée avec une <strong>immersion quotidienne active</strong>. Pour améliorer votre compréhension orale, écoutez quotidiennement des podcasts en français : <a href="https://www.rfi.fr/fr/podcasts/journal-en-fran%C3%A7ais-facile/" target="_blank">Journal en français facile (RFI)</a> propose un journal d'actualité de 10 minutes en français simplifié, idéal pour les niveaux A2-B1. <a href="https://www.innerfrench.com" target="_blank">InnerFrench</a> propose des discussions sur des sujets de société en français intermédiaire (B1-B2). <a href="https://www.france24.com/fr/" target="_blank">France24</a> et <a href="https://www.arte.tv/fr/" target="_blank">Arte</a> proposent des documentaires et reportages avec sous-titres en français. Pour la lecture, commencez par des <strong>bandes dessinées</strong> (Astérix, Tintin, Lucky Luke) disponibles dans toutes les bibliothèques municipales gratuitement, puis passez aux romans jeunesse (Le Petit Prince, Le Petit Nicolas) avant d'aborder la littérature contemporaine. Les bibliothèques universitaires et municipales sont entièrement gratuites et offrent un accès à des milliers de livres, magazines, et ressources numériques.</p>

<p>Pour pratiquer l'expression orale, inscrivez-vous aux <strong>tandems linguistiques</strong> proposés par la plupart des universités : vous aidez un étudiant français dans votre langue maternelle, et il vous aide en français. Les <strong>cafés des langues</strong> organisés dans de nombreuses villes (consultez Meetup ou Facebook Events) permettent de pratiquer dans une ambiance détendue. Sur le plan formel, les <strong>certifications officielles de français</strong> sont essentielles pour votre parcours. Le <strong>DELF (Diplôme d'Etudes en Langue Française)</strong> certifie les niveaux A1 à B2, tandis que le <strong>DALF (Diplôme Approfondi de Langue Française)</strong> certifie les niveaux C1 et C2. Le DELF B2 est généralement requis pour l'admission en licence dans les universités françaises, et le DALF C1 pour les masters. Le <strong>TCF (Test de Connaissance du Français)</strong> est une alternative plus rapide mais dont la validité est limitée à 2 ans (contre une validité à vie pour le DELF/DALF). Les centres d'examen sont présents dans toutes les grandes villes. Consultez le <a href="https://www.france-education-international.fr" target="_blank">France Education International</a> pour les dates et les tarifs. De nombreuses universités proposent des cours de FLE (Français Langue Etrangère) gratuits ou à tarif réduit pour les étudiants inscrits.</p>`,

fiscal: `
<h3>La déclaration d'impôts pour les étudiants internationaux</h3>
<p>Tout étudiant international résidant en France plus de 183 jours par an est considéré comme <strong>résident fiscal français</strong> et doit déclarer ses revenus chaque année, même s'ils sont nuls. La première déclaration se fait en créant un compte sur <a href="https://www.impots.gouv.fr" target="_blank">impots.gouv.fr</a> (service en ligne) ou en se rendant au Service des Impôts des Particuliers (SIP) de votre domicile. Les revenus déclarés comprennent : les salaires (déjà pré-remplis grâce aux déclarations de votre employeur), les gratifications de stage (exonérées jusqu'au SMIC annuel brut), les bourses (exonérées si elles proviennent de l'Etat français ou d'un organisme public), et les revenus du patrimoine. Les étudiants de moins de 25 ans peuvent choisir d'être rattachés au foyer fiscal de leurs parents (si ceux-ci sont résidents fiscaux français) ou de faire leur propre déclaration. En tant que déclarant indépendant, vous bénéficiez d'une <strong>décote</strong> et d'avantages fiscaux propres aux faibles revenus. Le barème de l'impôt sur le revenu est progressif. Avec un job étudiant au SMIC (temps partiel), vous serez très probablement non imposable.</p>

<p>L'<strong>avis d'imposition</strong> (ou avis de situation déclarative pour les non-imposables) est un document administratif essentiel en France. Il vous sera demandé pour : la demande d'APL à la CAF, la demande de bourse du CROUS, la demande de titre de séjour, la location d'un appartement, et parfois l'ouverture d'un compte bancaire. Même si vous n'avez aucun revenu, faites votre déclaration pour obtenir ce document. La <strong>taxe d'habitation</strong> a été supprimée pour les résidences principales, et la <strong>contribution à l'audiovisuel public (redevance TV)</strong> a également été supprimée. La <strong>taxe foncière</strong> ne concerne que les propriétaires et ne vous concerne donc pas en tant que locataire. En revanche, la <strong>taxe sur les logements vacants</strong> et la <strong>taxe d'enlèvement des ordures ménagères (TEOM)</strong> peuvent être répercutées par le propriétaire dans les charges locatives. Les conventions fiscales bilatérales entre la France et votre pays d'origine peuvent vous exonérer de double imposition. Consultez le site des impôts ou un conseiller fiscal pour vérifier votre situation spécifique.</p>`,

aides: `
<h3>Les aides financières spécifiques aux étudiants internationaux</h3>
<p>Au-delà des bourses du CROUS (réservées principalement aux étudiants de nationalité française ou européenne), les étudiants internationaux en France peuvent bénéficier de nombreuses aides financières. La <strong>bourse Eiffel</strong> du Ministère de l'Europe et des Affaires Etrangères est l'une des plus prestigieuses : elle finance les étudiants étrangers en master et en doctorat dans les domaines des sciences, de l'ingénierie, du droit, de l'économie et de la gestion politique. Les candidatures sont déposées par les établissements d'enseignement supérieur français, pas par les étudiants directement. La <strong>bourse Emile Boutmy</strong> de Sciences Po Paris, les bourses d'excellence de l'<strong>X (Ecole Polytechnique)</strong>, et les bourses des Grandes Ecoles sont accessibles aux étudiants internationaux sur critères académiques. Votre ambassade de France dans votre pays d'origine gère également des programmes de bourses spécifiques. Consultez le site <a href="https://www.campusfrance.org/fr/bourses" target="_blank">Campus France</a> pour un répertoire complet.</p>

<p>Les <strong>aides d'urgence</strong> sont accessibles à tous les étudiants, y compris internationaux, en cas de difficulté financière ponctuelle. Le <strong>CROUS</strong> dispose d'un fonds d'aide d'urgence accessible sur demande auprès du service social du CROUS. L'aide spécifique annuelle (versée pendant 10 mois, montant variable) est destinée aux étudiants en rupture familiale ou en situation de précarité durable. Les <strong>aides alimentaires</strong> sont accessibles via les épiceries solidaires étudiantes (AGORAé, présentes sur de nombreux campus), les <a href="https://www.restosducoeur.org" target="_blank">Restos du Coeur</a>, le <a href="https://www.secourspopulaire.fr" target="_blank">Secours Populaire</a>, et la <a href="https://www.banquealimentaire.org" target="_blank">Banque Alimentaire</a>. Le <strong>repas à 1 euro au CROUS</strong> (accessible aux boursiers et aux étudiants en situation de précarité) permet de manger un repas complet (entrée, plat, dessert) dans tous les restaurants universitaires. L'aide au <strong>permis de conduire</strong> est accessible aux personnes de plus de 17 ans résidant en France. Enfin, les <a href="https://www.actionlogement.fr" target="_blank">aides Action Logement</a> (avance Loca-Pass pour le dépôt de garantie, aide Mobili-Jeune pour les alternants) complètent le dispositif d'aides disponible.</p>`,

universite: `
<h3>Réussir à l'université française : méthodologie et ressources</h3>
<p>Le système universitaire français a ses propres codes et méthodes de travail qui peuvent dérouter les étudiants internationaux habitués à d'autres systèmes. Les <strong>cours magistraux (CM)</strong> rassemblent souvent des centaines d'étudiants dans un amphithéâtre. L'enseignant présente un cours structuré que les étudiants doivent prendre en notes de manière autonome. Les <strong>travaux dirigés (TD)</strong> sont des séances en petits groupes (25-35 étudiants) où l'on applique les concepts vus en CM à travers des exercices, des cas pratiques et des discussions. La présence en TD est souvent obligatoire et contrôlée, tandis que les CM sont généralement en présence libre. Les <strong>travaux pratiques (TP)</strong> concernent principalement les filières scientifiques et impliquent des manipulations en laboratoire. La <strong>notation française</strong> sur 20 est réputée sévère : obtenir 14/20 est considéré comme très bien, 16/20 comme excellent, et 18/20 comme exceptionnel. La mention passable commence à 10/20, assez bien à 12/20, bien à 14/20, et très bien à 16/20.</p>

<p>Pour réussir vos examens, exploitez les ressources mises à votre disposition. Les <strong>annales d'examens</strong> des années précédentes sont souvent disponibles au BDE (Bureau Des Etudiants) ou à la bibliothèque universitaire. Les <strong>tutorats</strong> organisés par les étudiants de deuxième et troisième année offrent un accompagnement gratuit en petits groupes. Les <strong>bibliothèques universitaires (BU)</strong> proposent des salles de travail en groupe, des postes informatiques, un accès WiFi, et des collections numériques accessibles à distance avec vos identifiants universitaires. Le service <strong>MOOC</strong> de <a href="https://www.fun-mooc.fr" target="_blank">FUN (France Université Numérique)</a> propose des cours en ligne gratuits dispensés par les meilleures universités françaises, parfaits pour compléter vos cours ou réviser. Le <strong>contrôle continu</strong> (devoirs, exposés, rendus) représente généralement 30 à 50% de la note finale, le reste étant constitué par les partiels de fin de semestre. Les <strong>sessions de rattrapage</strong> (deuxième chance) sont organisées en juin-juillet pour les étudiants n'ayant pas validé lors de la première session. Le système <strong>ECTS</strong> (European Credit Transfer System) est utilisé : chaque semestre valide 30 crédits ECTS, soit 60 par an, et un diplôme de licence représente 180 ECTS (3 ans), un master 300 ECTS (5 ans).</p>`,

securite: `
<h3>Sécurité personnelle et prévention en France</h3>
<p>La France est globalement un pays sûr, mais comme dans tout pays, il convient d'adopter des comportements préventifs. Les <strong>pickpockets</strong> sont actifs dans les zones touristiques et les transports en commun des grandes villes, particulièrement à Paris. Adoptez des réflexes simples : portez votre sac devant vous dans le métro, ne laissez pas votre téléphone sur la table au restaurant, méfiez-vous des personnes qui vous demandent de signer une pétition (technique de distraction courante). En cas de vol, portez plainte immédiatement au <strong>commissariat</strong> le plus proche ou en ligne sur <a href="https://www.pre-plainte-en-ligne.gouv.fr" target="_blank">pre-plainte-en-ligne.gouv.fr</a>. Le dépôt de plainte est gratuit et vous avez besoin du récépissé pour vos démarches d'assurance. Pour les objets volés ou perdus dans les transports en commun parisiens, consultez le <a href="https://www.ratp.fr/objets-trouves" target="_blank">service des objets trouvés de la RATP</a>. En cas de perte ou vol de votre téléphone, faites bloquer votre ligne en appelant votre opérateur et déposez une main courante au commissariat.</p>

<p>Le système d'alerte d'urgence <strong>FR-Alert</strong> envoie des notifications sur votre téléphone en cas de danger imminent (attentat, catastrophe naturelle, accident industriel) dans votre zone géographique. Ce système fonctionne automatiquement sur tous les téléphones mobiles, sans installation d'application. Les <strong>numéros d'urgence</strong> essentiels à mémoriser : <strong>15</strong> (SAMU), <strong>17</strong> (Police), <strong>18</strong> (Pompiers), <strong>112</strong> (numéro européen universel), <strong>114</strong> (urgence par SMS pour les personnes malentendantes ou dans l'impossibilité de parler). La <strong>Préfecture de police</strong> de votre département publie régulièrement des conseils de prévention adaptés aux risques locaux. Pour les étudiants victimes de <strong>discrimination</strong> (racisme, sexisme, homophobie), le <a href="https://www.defenseurdesdroits.fr" target="_blank">Défenseur des droits</a> est l'autorité indépendante compétente : vous pouvez le saisir gratuitement en ligne. SOS Racisme (<strong>01 40 35 36 55</strong>) et le <a href="https://www.licra.org" target="_blank">LICRA</a> offrent un accompagnement juridique gratuit aux victimes de discrimination raciale. L'association <a href="https://www.sos-homophobie.org" target="_blank">SOS Homophobie</a> propose une ligne d'écoute anonyme au <strong>01 48 06 42 41</strong>.</p>`,

culture: `
<h3>La vie culturelle et les loisirs à prix réduit en France</h3>
<p>La France offre un accès exceptionnel à la culture, souvent à prix réduit ou gratuit pour les étudiants et les jeunes. Les <strong>musées nationaux</strong> (Louvre, Orsay, Centre Pompidou, Quai Branly, etc.) sont <strong>gratuits pour tous les moins de 26 ans</strong> résidents de l'Espace économique européen, et pour tous les étudiants de l'Union européenne. Les étudiants internationaux hors UE bénéficient du tarif réduit (souvent 50% de réduction). Le premier dimanche de chaque mois, de nombreux musées nationaux sont gratuits pour tous. Le <a href="https://www.pass.culture.fr" target="_blank">Pass Culture</a> offre un crédit culturel aux jeunes de 18 ans (résidents en France depuis plus d'un an, de toute nationalité) utilisable pour des livres, spectacles, concerts, cinéma, cours de musique, etc. Les <strong>cinémas</strong> proposent des tarifs étudiants avantageux, et les cartes d'abonnement illimité (<a href="https://www.ugc.fr/illimite" target="_blank">UGC Illimité</a>, <a href="https://www.cgrcinemas.fr" target="_blank">CGR</a>, <a href="https://www.pathecinemas.com" target="_blank">Pathé</a>) permettent de voir autant de films que souhaité.</p>

<p>Le <strong>sport universitaire</strong> est très accessible en France. Le SUAPS (Service Universitaire des Activités Physiques et Sportives) de chaque université propose de nombreuses activités sportives gratuites ou à très faible coût : musculation, natation, sports collectifs, yoga, danse, arts martiaux, escalade, etc. La FFSU (Fédération Française du Sport Universitaire) organise des compétitions inter-universitaires dans plus de 50 disciplines. Pour le sport en ville, les piscines municipales sont très abordables au tarif réduit étudiant, les parcs et jardins publics offrent des terrains de sport en accès libre, et les applications comme <a href="https://www.decathlonactivities.com" target="_blank">Decathlon Activities</a> permettent de trouver des partenaires de sport près de chez vous. Pour les sorties, la vie nocturne française est variée : les <strong>happy hours</strong> (généralement de 17h à 20h) offrent des boissons à moitié prix dans de nombreux bars, les <strong>soirées étudiantes</strong> organisées par les BDE proposent des tarifs très réduits, et les festivals d'été (Solidays, Rock en Seine, Les Eurockéennes, Les Vieilles Charrues) proposent souvent des tarifs jeunes ou des places de bénévoles (entrée gratuite en échange de quelques heures de travail).</p>`,

pratique: `
<h3>La vie numérique et les services en ligne en France</h3>
<p>La France dispose d'une infrastructure numérique moderne et de nombreux services en ligne qui facilitent la vie quotidienne. Pour la <strong>téléphonie mobile</strong>, les opérateurs low-cost offrent les meilleurs rapports qualité-prix : <a href="https://www.free.fr/freemobile/" target="_blank">Free Mobile</a> propose un forfait très abordable avec appels, SMS et data inclus. <a href="https://www.red-by-sfr.fr" target="_blank">RED by SFR</a>, <a href="https://www.sosh.fr" target="_blank">Sosh</a> (Orange) et <a href="https://www.b-and-you.fr" target="_blank">B&You</a> (Bouygues) proposent des offres similaires sans engagement. Pour l'<strong>internet fixe</strong>, la fibre optique est disponible dans plus de 80% des foyers français et coûte entre 20 et 35 euros par mois (box internet + téléphone fixe + TV). Les résidences étudiantes CROUS et privées disposent généralement d'un accès WiFi inclus dans le loyer. Le réseau <strong>eduroam</strong> vous permet d'accéder au WiFi dans toutes les universités et institutions de recherche participantes dans le monde entier avec vos identifiants universitaires français.</p>

<p>Pour la gestion de vos <strong>documents administratifs</strong>, les applications suivantes sont indispensables : <a href="https://www.ameli.fr" target="_blank">Ameli</a> (Sécurité sociale), <a href="https://www.caf.fr" target="_blank">CAF</a> (suivi de vos aides au logement), <a href="https://www.impots.gouv.fr" target="_blank">impots.gouv.fr</a> (déclaration d'impôts, avis d'imposition), <a href="https://www.messervices.etudiant.gouv.fr" target="_blank">MesServices.etudiant.gouv.fr</a> (dossier social étudiant, bourse, logement CROUS). Pour les <strong>achats du quotidien</strong>, plusieurs applications vous feront économiser : <a href="https://www.toogoodtogo.com/fr" target="_blank">Too Good To Go</a> permet d'acheter des paniers de nourriture invendue à prix réduit dans les boulangeries, supermarchés et restaurants. <a href="https://www.igraal.com" target="_blank">iGraal</a> et <a href="https://www.poulpeo.com" target="_blank">Poulpeo</a> offrent du cashback sur les achats en ligne. Les <strong>bons plans étudiants</strong> sont répertoriés sur <a href="https://www.studentbeans.com/fr" target="_blank">Student Beans</a> et <a href="https://www.unidays.com/fr-FR" target="_blank">UNiDAYS</a> (réductions exclusives étudiants chez Apple, ASOS, Spotify, Samsung, etc.).</p>

<h3>Se déplacer dans la ville et découvrir son quartier</h3>
<p>Pour bien s'intégrer dans votre nouvelle ville française, familiarisez-vous rapidement avec votre quartier et ses ressources. La <strong>mairie de quartier</strong> (ou mairie d'arrondissement dans les grandes villes) est votre premier interlocuteur local pour les questions pratiques : carte de stationnement, inscription sur les listes électorales consulaires, activités municipales. Les <strong>Maisons des Jeunes et de la Culture (MJC)</strong> et les <strong>centres sociaux</strong> proposent des activités culturelles, sportives et sociales à tarifs très réduits : cours de danse, de musique, de théâtre, ateliers d'art, sorties culturelles, événements de quartier. Les <strong>marchés</strong> (alimentaires et non-alimentaires) sont une institution française : ils ont lieu généralement 2 à 3 fois par semaine dans chaque quartier et proposent des produits frais souvent moins chers qu'en supermarché, surtout en fin de marché (les vendeurs baissent les prix pour écouler les stocks). Les <strong>AMAP (Associations pour le Maintien d'une Agriculture Paysanne)</strong> proposent des paniers de fruits et légumes de saison et locaux à prix abordables, livrés chaque semaine dans un point de distribution près de chez vous.</p>`
};

function generateExtra(topic) {
  return pass3Blocks[topic] || pass3Blocks.pratique;
}

async function main() {
  console.log('=== PASS 3: Final enrichment ===');
  console.log('Fetching all lessons...');
  const allLessons = await fetchAll();
  console.log(`Total lessons: ${allLessons.length}`);

  const coursesRes = await fetch(`${SUPABASE_URL}/rest/v1/courses?select=id,title`, { headers: H });
  const courses = await coursesRes.json();
  const courseMap = {};
  courses.forEach(c => { courseMap[c.id] = c.title; });

  const under = allLessons.filter(l => l.content.split(' ').length < 4000);
  under.sort((a, b) => a.content.split(' ').length - b.content.split(' ').length);
  console.log(`${under.length} lessons still under 4000 words`);
  if (under.length > 0) {
    console.log(`Shortest: ${under[0].content.split(' ').length} words`);
    console.log(`Longest under 4000: ${under[under.length-1].content.split(' ').length} words`);
  }

  let success = 0, fail = 0;
  for (const l of under) {
    const courseTitle = courseMap[l.course_id] || '';
    const topic = getTopic(l.title, courseTitle);
    const extra = generateExtra(topic);
    const enriched = l.content + '\n\n' + extra;

    const status = await update(l.id, enriched);
    if (status === 204) {
      success++;
      if (success % 50 === 0) console.log(`... ${success} enriched`);
    } else {
      fail++;
      console.log(`FAIL: ${l.title} (${status})`);
    }
  }

  console.log(`\n=== PASS 3 DONE ===`);
  console.log(`Enriched: ${success} | Failed: ${fail}`);

  // Distribution check
  const all2 = await fetchAll();
  const wcs = all2.map(l => l.content.split(' ').length);
  const buckets = {'0-2000':0,'2000-3000':0,'3000-4000':0,'4000-5000':0,'5000-7000':0,'7000+':0};
  wcs.forEach(w => {
    if (w<2000) buckets['0-2000']++;
    else if (w<3000) buckets['2000-3000']++;
    else if (w<4000) buckets['3000-4000']++;
    else if (w<5000) buckets['4000-5000']++;
    else if (w<7000) buckets['5000-7000']++;
    else buckets['7000+']++;
  });
  console.log('\nFinal distribution:', JSON.stringify(buckets, null, 2));
  console.log(`Above 4000: ${wcs.filter(w=>w>=4000).length} / ${all2.length}`);
  console.log(`Min: ${Math.min(...wcs)} | Max: ${Math.max(...wcs)}`);
}

main().catch(console.error);
