// Second pass: enrichissement massif pour atteindre 4000+ mots
// Ajoute des sections DIFFERENTES du premier passage
const SUPABASE_URL = 'https://xkecqmsgvjjtujvlotpm.supabase.co';
const SK = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZWNxbXNndmpqdHVqdmxvdHBtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjU4NDIxNSwiZXhwIjoyMDgyMTYwMjE1fQ.jOOgWSgXTqOKtr1fFqh4RIhwXzd7ZcF9XjOihpCHCnU';
const H = { 'apikey': SK, 'Authorization': `Bearer ${SK}`, 'Content-Type': 'application/json' };

async function fetchAll() {
  let all = [], offset = 0;
  while (true) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/lessons?select=id,title,content,course_id&limit=100&offset=${offset}`, { headers: H });
    const data = await res.json();
    if (!data.length) break;
    all = all.concat(data);
    offset += 100;
  }
  return all;
}

async function update(id, content) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/lessons?id=eq.${id}`, {
    method: 'PATCH', headers: { ...H, 'Prefer': 'return=minimal' },
    body: JSON.stringify({ content })
  });
  return res.status;
}

function getTopic(title, courseTitle) {
  const t = (title + ' ' + (courseTitle||'')).toLowerCase();
  if (t.includes('logement') || t.includes('bail') || t.includes('locat') || t.includes('caution') || t.includes('préavis') || t.includes('demenag') || t.includes('déménag') || t.includes('état des lieux') || t.includes('garant') || t.includes('visale') || t.includes('copropri') || t.includes('annonce') || t.includes('meublé') || t.includes('colocation') || t.includes('énergie') || t.includes('compteur') || t.includes('assurance habitation') || t.includes('internet') || t.includes('fibre')) return 'logement';
  if (t.includes('banqu') || t.includes('bancaire') || t.includes('rib') || t.includes('chequ') || t.includes('frais') || t.includes('agios') || t.includes('clôturer') || t.includes('carte bancaire') || t.includes('virement') || t.includes('compte')) return 'banque';
  if (t.includes('transport') || t.includes('navigo') || t.includes('velib') || t.includes('vélib') || t.includes('sncf') || t.includes('train') || t.includes('voyag') || t.includes('trottinette') || t.includes('metro') || t.includes('bus')) return 'transport';
  if (t.includes('cv') || t.includes('emploi') || t.includes('travail') || t.includes('job') || t.includes('lettre') || t.includes('motivation') || t.includes('alternance') || t.includes('stage') || t.includes('statut') || t.includes('salari') || t.includes('linkedin') || t.includes('network') || t.includes('alumni') || t.includes('entretien') || t.includes('candidat') || t.includes('auto-entrepreneur') || t.includes('pôle emploi') || t.includes('télétravail') || t.includes('législation')) return 'emploi';
  if (t.includes('santé') || t.includes('sante') || t.includes('carte vitale') || t.includes('médecin') || t.includes('cpam') || t.includes('sécu') || t.includes('mutuelle') || t.includes('rembours') || t.includes('pharma') || t.includes('doctolib') || t.includes('lunettes') || t.includes('dents') || t.includes('sexuel') || t.includes('psycho') || t.includes('ofii') || t.includes('soins') || t.includes('ifsi')) return 'sante';
  if (t.includes('préfecture') || t.includes('titre') || t.includes('visa') || t.includes('vls') || t.includes('anef') || t.includes('campus france') || t.includes('renouvellement') || t.includes('identit') || t.includes('légalisation') || t.includes('permis') || t.includes('service-public') || t.includes('aps') || t.includes('région') || t.includes('checklist') || t.includes('départ')) return 'administratif';
  if (t.includes('français') || t.includes('francais') || t.includes('delf') || t.includes('dalf') || t.includes('b1') || t.includes('b2') || t.includes('a1') || t.includes('grammaire') || t.includes('prononciation')) return 'francais';
  if (t.includes('impôt') || t.includes('impot') || t.includes('fiscal') || t.includes('taxe') || t.includes('avis') || t.includes('teom')) return 'fiscal';
  if (t.includes('caf') || t.includes('apl') || t.includes('aide') || t.includes('bourse')) return 'aides';
  if (t.includes('universi') || t.includes('examen') || t.includes('inscription') || t.includes('campus') || t.includes('études')) return 'universite';
  if (t.includes('urgence') || t.includes('secours') || t.includes('sécurité') || t.includes('pickpocket') || t.includes('objets')) return 'securite';
  if (t.includes('bise') || t.includes('tu ou vous') || t.includes('politesse') || t.includes('apéro') || t.includes('café') || t.includes('boulangerie') || t.includes('pourboire') || t.includes('cinéma') || t.includes('grève') || t.includes('férié') || t.includes('association') || t.includes('amis') || t.includes('lgbtq') || t.includes('tabac') || t.includes('alcool') || t.includes('laïcité') || t.includes('codes sociaux') || t.includes('pass culture') || t.includes('resto') || t.includes('repas') || t.includes('coiffeur') || t.includes('animaux') || t.includes('laver') || t.includes('laverie') || t.includes('poste') || t.includes('occasion') || t.includes('tri') || t.includes('budget') || t.includes('manger') || t.includes('courses') || t.includes('forfait') || t.includes('mobile')) return 'culture';
  return 'pratique';
}

// Bloc 2 d'enrichissement — sections DIFFERENTES du premier passage
const extraBlocks = {
  logement: `
<h3>Le bail étudiant et le bail mobilité : deux options flexibles</h3>
<p>La France propose deux types de bail particulièrement adaptés aux étudiants internationaux qui recherchent de la flexibilité dans leur engagement locatif. Le <strong>bail étudiant</strong> est un contrat de location meublée d'une durée de 9 mois, non reconductible automatiquement, spécialement conçu pour correspondre à l'année universitaire. Ce bail offre l'avantage de ne pas obliger l'étudiant à rester pendant l'été s'il souhaite rentrer dans son pays d'origine. Le propriétaire ne peut pas s'opposer au départ de l'étudiant à la fin des 9 mois, ce qui garantit une sécurité juridique totale. Pour pouvoir bénéficier de ce bail, l'étudiant doit fournir une carte d'étudiant ou un certificat de scolarité valide lors de la signature du contrat. Le loyer et les charges sont fixés dans le contrat et ne peuvent pas être augmentés en cours de bail, sauf si une clause de révision annuelle est prévue et indexée sur l'<a href="https://www.insee.fr/fr/statistiques/serie/001515333" target="_blank">Indice de Référence des Loyers (IRL)</a> publié par l'INSEE chaque trimestre.</p>

<p>Le <strong>bail mobilité</strong>, instauré par la loi ELAN du 23 novembre 2018, est encore plus souple. Il s'adresse aux personnes en formation professionnelle, en études supérieures, en apprentissage, en stage, en engagement volontaire dans le cadre d'un service civique, en mutation professionnelle, ou en mission temporaire. Sa durée est libre entre 1 et 10 mois, et il n'est ni renouvelable ni reconductible. L'avantage majeur de ce bail est qu'<strong>aucun dépôt de garantie ne peut être exigé</strong> par le propriétaire, ce qui représente une économie substantielle à l'entrée dans le logement (souvent 1 à 2 mois de loyer). En revanche, le propriétaire peut demander que le locataire soit couvert par la <a href="https://www.visale.fr" target="_blank">garantie VISALE</a>, un dispositif gratuit d'Action Logement qui se porte caution pour le locataire. Ce dispositif est accessible à tous les étudiants de moins de 30 ans, quelle que soit leur nationalité, ce qui en fait un outil précieux pour les étudiants internationaux n'ayant pas de garant en France.</p>

<h3>La colocation en France : aspects juridiques et pratiques</h3>
<p>La colocation est devenue une solution incontournable pour les étudiants dans les grandes villes françaises, permettant de réduire significativement le coût du logement tout en bénéficiant d'un espace de vie plus grand et d'une expérience sociale enrichissante. Sur le plan juridique, la colocation peut prendre deux formes distinctes :</p>
<ul>
<li><strong>Le bail unique</strong> (bail solidaire) : tous les colocataires signent le même contrat. Une clause de solidarité oblige chaque colocataire à payer la totalité du loyer si les autres ne paient pas leur part. Cette solidarité prend fin 6 mois après le départ effectif d'un colocataire (si un remplaçant est trouvé) ou à la fin du préavis. C'est la forme la plus courante, mais aussi la plus risquée financièrement.</li>
<li><strong>Les baux individuels</strong> : chaque colocataire signe un contrat séparé avec le propriétaire pour sa chambre, avec jouissance partagée des parties communes. Il n'y a pas de solidarité entre colocataires, et chacun est responsable uniquement de sa propre part de loyer. C'est la forme la plus protectrice pour les locataires.</li>
</ul>
<p>En colocation, chaque colocataire peut faire sa propre demande d'APL auprès de la <a href="https://www.caf.fr" target="_blank">CAF</a>, sur la base de sa quote-part de loyer. Le dépôt de garantie en colocation est au maximum d'un mois de loyer total (et non d'un mois par colocataire). Les plateformes de colocation les plus utilisées en France sont <a href="https://www.lacartedescolocs.fr" target="_blank">La Carte des Colocs</a>, <a href="https://www.appartager.com" target="_blank">Appartager</a>, et les groupes Facebook dédiés à chaque ville universitaire. Avant de s'engager, il est vivement recommandé de visiter le logement, de rencontrer les futurs colocataires, et de vérifier l'état du logement et des équipements. Un état des lieux d'entrée détaillé est indispensable en colocation, car les dégradations des parties communes peuvent être imputées à tous les colocataires solidaires.</p>

<h3>Les démarches d'installation : eau, électricité, internet</h3>
<p>Une fois le bail signé et les clés en main, plusieurs démarches sont nécessaires pour rendre le logement habitable et fonctionnel. Pour l'<strong>électricité</strong>, le marché est ouvert à la concurrence depuis 2007. Vous pouvez choisir entre le fournisseur historique EDF et des fournisseurs alternatifs comme Engie, TotalEnergies, Eni, ou des fournisseurs verts comme Enercoop ou Planète Oui. La mise en service coûte environ 14€ (sous 5 jours ouvrés) ou 52€ pour une mise en service express (sous 24h). Pour souscrire, vous aurez besoin du numéro de Point de Livraison (PDL) inscrit sur le compteur ou dans l'état des lieux, et du relevé de compteur. La procédure se fait entièrement en ligne ou par téléphone sur <a href="https://www.edf.fr" target="_blank">edf.fr</a> ou le site du fournisseur choisi.</p>

<p>Pour le <strong>gaz</strong>, la démarche est similaire. Le distributeur unique est GRDF, mais vous pouvez choisir votre fournisseur (Engie, EDF, TotalEnergies, etc.). La mise en service coûte environ 19€. Si le compteur a été coupé, un technicien GRDF devra se déplacer pour la remise en service, ce qui peut prendre quelques jours.</p>

<p>Pour l'<strong>internet</strong>, les quatre principaux opérateurs sont Orange, Free, SFR et Bouygues Telecom. La fibre optique est disponible dans la majorité des logements en zone urbaine, avec des débits allant de 300 Mbit/s à 8 Gbit/s selon l'offre. Les prix varient de 16€/mois (Free) à 45€/mois (Orange Livebox Up). Vérifiez l'éligibilité de votre adresse sur le site de chaque opérateur ou sur <a href="https://www.ariase.com/box/test-eligibilite" target="_blank">Ariase</a>. L'installation de la fibre nécessite souvent le passage d'un technicien (gratuit), comptez 1 à 3 semaines de délai. En attendant, votre forfait mobile 4G/5G peut servir de point d'accès internet temporaire.</p>

<p>Pour l'<strong>eau</strong>, le contrat est généralement au nom du propriétaire pour les appartements en copropriété. Si vous êtes en maison individuelle, contactez la régie locale (Veolia, Suez, ou régie municipale) pour mettre le compteur à votre nom. Le prix de l'eau en France varie de 3€ à 6€/m³ selon les communes.</p>

<h3>L'assurance habitation : une obligation légale</h3>
<p>L'assurance habitation est <strong>obligatoire</strong> pour tout locataire en France, qu'il s'agisse d'un logement vide ou meublé. Le propriétaire peut exiger une attestation d'assurance à la signature du bail et à chaque renouvellement annuel. Le défaut d'assurance peut entraîner la résiliation du bail. L'assurance habitation couvre au minimum la <strong>responsabilité civile locative</strong> (dégâts que vous pourriez causer au logement et aux voisins, comme un dégât des eaux ou un incendie). Des garanties complémentaires (vol, bris de glace, catastrophe naturelle) sont recommandées. Les assureurs étudiants comme <a href="https://www.heyme.care" target="_blank">HEYME</a>, la <a href="https://www.maif.fr" target="_blank">MAIF</a>, ou <a href="https://www.luko.eu/fr" target="_blank">Luko</a> proposent des contrats à partir de 3€/mois pour un studio. Comparez les offres sur <a href="https://www.lesfurets.com/assurance-habitation" target="_blank">LesFurets</a> ou <a href="https://www.lelynx.fr/assurance-habitation/" target="_blank">LeLynx</a>.</p>`,

  banque: `
<h3>Les spécificités bancaires pour les étudiants non-européens</h3>
<p>L'ouverture d'un compte bancaire en France pour un étudiant hors Union Européenne présente quelques particularités qu'il est important de connaître. Contrairement aux citoyens européens qui peuvent ouvrir un compte dans n'importe quelle banque avec un simple passeport, les étudiants extra-européens doivent généralement présenter un <strong>titre de séjour valide</strong> (ou un visa long séjour) en plus de leur passeport. Certaines banques demandent également un justificatif de domicile et un certificat de scolarité. En pratique, la <strong>Banque Postale</strong> est souvent la plus facile d'accès pour les primo-arrivants, car elle accepte les justificatifs provisoires et dispose de bureaux dans tout le pays. Le <strong>Crédit Mutuel</strong> et le <strong>CIC</strong> sont également réputés pour leur accueil des étudiants internationaux, avec des conseillers spécialisés dans certaines agences proches des campus universitaires.</p>

<p>Si vous ne parvenez pas à ouvrir un compte dans une banque traditionnelle, vous disposez de deux recours importants. Le premier est le <strong>droit au compte</strong>, garanti par l'article L312-1 du Code monétaire et financier. Si une banque vous refuse l'ouverture d'un compte (ce qui doit être notifié par écrit), vous pouvez saisir la <a href="https://www.banque-france.fr/page-sommaire/droit-au-compte" target="_blank">Banque de France</a> qui désignera d'office un établissement bancaire. Le second recours consiste à utiliser une <strong>néo-banque</strong> comme Nickel (comptes disponibles dans les bureaux de tabac, ouverture en 5 minutes avec un simple passeport, sans condition de revenus ni de résidence), ou Revolut/N26 (ouverture en ligne depuis l'application mobile). Ces solutions sont particulièrement pratiques pour les premiers jours en France, avant d'avoir un justificatif de domicile.</p>

<h3>La gestion budgétaire et les outils numériques</h3>
<p>La gestion de son budget est un défi majeur pour tout étudiant international en France, d'autant plus que les frais de la vie quotidienne peuvent varier considérablement selon les villes. À Paris, le budget mensuel moyen d'un étudiant se situe entre 1 000€ et 1 500€ (loyer inclus), tandis qu'en province, il peut descendre à 700-1 000€. Plusieurs applications de gestion budgétaire sont particulièrement populaires en France et peuvent vous aider à suivre vos dépenses. <strong>Bankin'</strong> est une application française gratuite qui agrège tous vos comptes bancaires et catégorise automatiquement vos dépenses. <strong>Linxo</strong> offre des fonctionnalités similaires avec une interface particulièrement intuitive. L'application <strong>Pilote Budget</strong>, développée par l'Institut National de la Consommation, est gratuite et conçue spécifiquement pour les personnes à revenus modestes. Elle propose des alertes quand vos dépenses dépassent les seuils que vous avez fixés.</p>

<p>Pour les transferts d'argent internationaux (réception d'argent de votre famille, par exemple), les solutions les plus économiques sont <a href="https://wise.com/fr/" target="_blank">Wise</a> (anciennement TransferWise), qui applique le taux de change réel avec une commission transparente de 0,4% à 1%, et <a href="https://www.worldremit.com/fr" target="_blank">WorldRemit</a>, particulièrement avantageux pour les transferts vers l'Afrique et l'Asie. Évitez les bureaux de change physiques et les services comme Western Union ou MoneyGram dont les frais sont nettement plus élevés. Pour les paiements quotidiens, le <strong>paiement sans contact</strong> est accepté quasiment partout en France (plafond de 50€ par transaction). Apple Pay, Google Pay et Samsung Pay sont largement supportés par les banques françaises et les néo-banques.</p>

<h3>Comprendre votre fiche de paie française</h3>
<p>Si vous travaillez en France (job étudiant, stage rémunéré, alternance), vous recevrez une <strong>fiche de paie</strong> chaque mois, un document souvent complexe à décrypter. Voici les lignes essentielles à comprendre :</p>
<table>
<tr><th>Ligne</th><th>Signification</th></tr>
<tr><td>Salaire brut</td><td>Votre rémunération avant toutes déductions. C'est le montant indiqué dans votre contrat.</td></tr>
<tr><td>Cotisations salariales</td><td>Environ 22% du brut, prélevées pour financer la Sécurité Sociale, la retraite, le chômage, la CSG/CRDS.</td></tr>
<tr><td>Salaire net avant impôt</td><td>Brut moins cotisations. C'est ce que vous « gagnez » réellement.</td></tr>
<tr><td>Prélèvement à la source</td><td>Impôt sur le revenu prélevé directement. Le taux est de 0% la première année (taux neutre) si vous n'avez pas encore déclaré.</td></tr>
<tr><td>Net à payer</td><td>Le montant réellement viré sur votre compte bancaire.</td></tr>
</table>
<p>Pour un SMIC horaire brut de 11,65€, le net est d'environ 9,22€ après cotisations. Sur un job étudiant de 15h/semaine, cela représente environ 550-600€ net/mois. Conservez toutes vos fiches de paie car elles servent de justificatif pour de nombreuses démarches (déclaration d'impôts, demande de logement, demande de titre de séjour salarié, etc.).</p>`,

  transport: `
<h3>Les cartes de réduction et abonnements pour étudiants</h3>
<p>La France propose un éventail de cartes de réduction sur les transports qui permettent aux étudiants de réaliser des économies considérables. La <strong>carte Avantage Jeune SNCF</strong> (49€/an, pour les 12-27 ans) offre 30% de réduction garantie sur tous les trains TGV INOUI et Intercités en France, et jusqu'à 25% sur les trajets internationaux. La carte est disponible sur <a href="https://www.sncf-connect.com" target="_blank">SNCF Connect</a> et est rentabilisée dès le premier aller-retour longue distance. Pour les trajets régionaux (TER), chaque région propose ses propres tarifs réduits pour les jeunes et les étudiants. En Île-de-France, le <strong>forfait Imagine R Étudiant</strong> (environ 380€/an après déduction, soit 31,60€/mois) donne accès à l'ensemble du réseau RATP et Transilien (métro, bus, RER, tramway) dans toutes les zones. La demande se fait en ligne sur <a href="https://www.iledefrance-mobilites.fr/titres-et-tarifs/imagine-r-etudiant" target="_blank">Île-de-France Mobilités</a>. À noter que les employeurs en France sont tenus de rembourser 50% du coût de l'abonnement de transport de leurs salariés, ce qui s'applique aussi aux étudiants en alternance ou en stage.</p>

<p>Pour les voyages en Europe, le <strong>pass Interrail</strong> est une option très populaire auprès des étudiants. Il existe en version « Global Pass » (accès à 33 pays européens) avec des tarifs jeune (-27 ans) à partir de 194€ pour 4 jours de voyage sur 1 mois, jusqu'à 493€ pour 3 mois de voyage illimité. Le pass est disponible sur <a href="https://www.interrail.eu/fr" target="_blank">interrail.eu</a>. Les compagnies aériennes low-cost comme <strong>EasyJet</strong>, <strong>Ryanair</strong>, <strong>Transavia</strong> et <strong>Vueling</strong> proposent régulièrement des vols à travers l'Europe à partir de 15-30€ l'aller simple. Réservez 2-3 mois à l'avance et soyez flexible sur les dates pour obtenir les meilleurs prix. Le site <a href="https://www.skyscanner.fr" target="_blank">Skyscanner</a> permet de comparer les prix sur toutes les compagnies et de trouver les destinations les moins chères depuis votre aéroport.</p>

<h3>Le permis de conduire en France pour les étudiants internationaux</h3>
<p>Si vous possédez un permis de conduire étranger, plusieurs règles s'appliquent en France. Les permis délivrés par un <strong>pays de l'Union Européenne ou de l'Espace Économique Européen</strong> sont directement reconnus en France et peuvent être utilisés pendant toute leur durée de validité, sans aucune formalité. Pour les permis délivrés par un <strong>pays hors UE</strong>, la situation est différente : votre permis étranger est valide en France pendant les <strong>12 premiers mois</strong> suivant l'obtention de votre premier titre de séjour, à condition qu'il soit accompagné d'une traduction officielle (faite par un traducteur assermenté). Passé ce délai, vous devez demander l'échange de votre permis étranger contre un permis français. Cette procédure dépend de l'existence d'un accord bilatéral entre la France et votre pays d'origine. Environ 100 pays ont signé de tels accords (liste complète sur <a href="https://www.service-public.fr/particuliers/vosdroits/F1460" target="_blank">service-public.fr</a>). Si votre pays n'a pas d'accord, vous devrez malheureusement repasser le permis de conduire français (formation en auto-école + examens du code et de la conduite).</p>

<p>Pour le <strong>covoiturage</strong>, la plateforme française <a href="https://www.blablacar.fr" target="_blank">BlaBlaCar</a> est le leader européen avec plus de 100 millions de membres. Le service est économique (un Paris-Lyon coûte environ 15-25€ en covoiturage contre 40-90€ en TGV), convivial, et assez sûr grâce au système de notation et de vérification des profils. BlaBlaCar propose aussi un service de bus (BlaBlaBus) avec des trajets à partir de 5€. Pour la location de voiture ponctuelle, les services d'autopartage comme <a href="https://www.getaround.com/fr" target="_blank">Getaround</a> (anciennement Drivy) permettent de louer la voiture d'un particulier à l'heure ou à la journée (souvent moins cher qu'un loueur traditionnel).</p>`,

  emploi: `
<h3>Les contrats de travail en France : guide détaillé</h3>
<p>Le droit du travail français distingue plusieurs types de contrats, chacun avec ses propres règles et protections. Le <strong>CDI (Contrat à Durée Indéterminée)</strong> est la forme « normale » du contrat de travail en France. Il n'a pas de date de fin prévue et offre la plus grande sécurité d'emploi. Le licenciement d'un salarié en CDI est encadré par des procédures strictes et ne peut intervenir que pour un motif réel et sérieux (faute, motif économique, inaptitude). Le <strong>CDD (Contrat à Durée Déterminée)</strong> est limité à 18 mois maximum (renouvellement inclus) et ne peut être utilisé que dans des cas précis : remplacement d'un salarié absent, accroissement temporaire d'activité, contrat saisonnier, ou emploi d'usage dans certains secteurs (hôtellerie, restauration, spectacle, audiovisuel). Le CDD ouvre droit à une <strong>prime de précarité</strong> de 10% du salaire brut total, versée à la fin du contrat. L'<strong>intérim</strong> (travail temporaire) est un contrat tripartite entre vous, une agence d'intérim (Adecco, Manpower, Randstad, etc.) et l'entreprise utilisatrice. Les agences d'intérim sont souvent une bonne porte d'entrée pour les étudiants car elles proposent des missions courtes et variées.</p>

<p>Le <strong>contrat d'apprentissage</strong> et le <strong>contrat de professionnalisation</strong> sont les deux formes de l'alternance. L'apprentissage est ouvert aux 16-29 ans (sans limite d'âge pour les étudiants internationaux hors UE) et combine formation en CFA et travail en entreprise. La rémunération varie de 27% à 100% du SMIC selon l'âge et l'année d'apprentissage. Le contrat de professionnalisation est ouvert à tous les demandeurs d'emploi de 16 ans et plus, avec une rémunération de 55% à 100% du SMIC. Les deux contrats permettent d'obtenir un diplôme tout en acquérant une expérience professionnelle rémunérée, et offrent les mêmes droits sociaux qu'un salarié classique (congés payés, Sécurité Sociale, cotisations retraite). La <a href="https://www.alternance.emploi.gouv.fr" target="_blank">plateforme du Portail de l'Alternance</a> du Ministère du Travail centralise les offres et les informations pratiques.</p>

<h3>L'entretien d'embauche à la française</h3>
<p>L'entretien d'embauche en France a ses codes spécifiques qu'il est important de maîtriser pour maximiser ses chances. La <strong>ponctualité</strong> est absolument essentielle : arrivez 5-10 minutes en avance, jamais en retard. La <strong>tenue vestimentaire</strong> varie selon le secteur : costume/tailleur pour la banque et le conseil, tenue « business casual » pour les startups et le digital, tenue soignée mais décontractée pour le commerce et la restauration. Serrez la main fermement en regardant votre interlocuteur dans les yeux. Vouvoyez systématiquement votre interlocuteur, sauf s'il vous propose le tutoiement. Les questions les plus fréquentes incluent : « Parlez-moi de vous » (préparez un pitch de 2-3 minutes), « Pourquoi cette entreprise ? » (montrez que vous avez fait des recherches), « Quels sont vos défauts ? » (choisissez un vrai défaut en montrant comment vous y travaillez), et « Où vous voyez-vous dans 5 ans ? » (montrez de l'ambition mais restez réaliste). Les questions sur la religion, l'orientation sexuelle, la situation familiale, l'état de santé ou les opinions politiques sont <strong>illégales</strong> en France – vous n'êtes pas obligé d'y répondre.</p>

<p>Après l'entretien, envoyez un <strong>email de remerciement</strong> dans les 24h, résumant les points clés de la conversation et réaffirmant votre motivation. Si vous n'avez pas de nouvelles après 2 semaines, relancez poliment par email ou téléphone. En France, le processus de recrutement peut prendre de 2 semaines (petites entreprises, restauration) à 2-3 mois (grandes entreprises, secteur public). Ne vous découragez pas si vous ne recevez pas de réponse : en France, le « ghosting » est malheureusement courant dans le recrutement, surtout pour les postes juniors.</p>`,

  sante: `
<h3>Les soins dentaires et optiques en France</h3>
<p>Les soins dentaires et optiques représentent souvent les postes de santé les plus coûteux pour les étudiants. Depuis 2021, le dispositif <strong>100% Santé</strong> garantit un panier de soins intégralement remboursé (Sécurité Sociale + mutuelle) pour les lunettes, les prothèses dentaires et les audioprothèses. Pour les <strong>lunettes</strong>, le panier 100% Santé comprend des montures à 30€ maximum et des verres correcteurs de toutes puissances, avec traitement anti-rayures et anti-reflets. Pour les <strong>prothèses dentaires</strong>, les couronnes céramo-métalliques et en céramique monolithique sur les dents visibles sont intégralement prises en charge. En dehors du panier 100% Santé, les tarifs sont libres et peuvent être très élevés (500-1500€ pour une couronne, 100-500€ pour une paire de lunettes). Les mutuelles étudiantes remboursent une partie de ces frais selon le niveau de couverture souscrit. Le site <a href="https://www.ameli.fr/assure/remboursements/rembourse/optique-dentaire/prothese-couronne-dentaire" target="_blank">ameli.fr</a> détaille les taux de remboursement pour chaque type de soin.</p>

<p>Pour les soins <strong>psychologiques</strong>, le dispositif <strong>MonParcoursPsy</strong> (anciennement MonPsy) permet de bénéficier de 8 séances par an remboursées par la Sécurité Sociale, sur prescription du médecin traitant. Le site <a href="https://monparcourspsy.sante.gouv.fr" target="_blank">monparcourspsy.sante.gouv.fr</a> recense les psychologues conventionnés. Les <strong>Services de Santé Universitaires (SSU)</strong> proposent également des consultations psychologiques gratuites pour les étudiants, souvent avec des délais de rendez-vous plus courts que dans le système de ville. Le programme <strong>Nightline</strong>, disponible dans de nombreuses villes universitaires, offre un service d'écoute nocturne gratuit et anonyme, par et pour les étudiants (appel ou tchat de 21h à 2h30). La <a href="https://www.nightline.fr" target="_blank">Nightline France</a> est joignable au 0 800 130 000.</p>

<h3>La pharmacie en France : mode d'emploi</h3>
<p>Les pharmacies françaises, reconnaissables à leur <strong>croix verte lumineuse</strong>, sont bien plus que de simples points de vente de médicaments. Les pharmaciens français sont des professionnels de santé habilités à délivrer des conseils médicaux, à effectuer certains tests de dépistage (Covid, angine, grippe), à vacciner, et à renouveler certaines ordonnances expirées pour les traitements chroniques (contraception, hypertension, diabète). Les médicaments se divisent en deux catégories : ceux <strong>sur ordonnance</strong> (antibiotiques, antidépresseurs, etc.) qui nécessitent une prescription médicale et sont remboursés par la Sécurité Sociale selon leur classification (vignette blanche : 65%, vignette bleue : 30%), et ceux <strong>en automédication</strong> (paracétamol, ibuprofène, etc.) vendus sans ordonnance et généralement non remboursés. La France est le premier pays européen pour la consommation de médicaments par habitant. Les pharmacies de garde assurent un service 24h/24 et 7j/7 : trouvez la plus proche sur <a href="https://www.3237.fr" target="_blank">3237.fr</a> ou en appelant le 3237.</p>`,

  administratif: `
<h3>Le système administratif français : comprendre la bureaucratie</h3>
<p>L'administration française, souvent perçue comme complexe et lourde, repose sur un système hiérarchique structuré à plusieurs niveaux. Au niveau national, les <strong>ministères</strong> définissent les politiques publiques et les grands cadres réglementaires. Au niveau régional, les <strong>préfectures de région</strong> et les services déconcentrés de l'État (DIRECCTE pour le travail, ARS pour la santé, rectorat pour l'éducation) mettent en œuvre ces politiques. Au niveau départemental, les <strong>préfectures</strong> et sous-préfectures gèrent les titres de séjour, les permis de conduire, et d'autres démarches administratives. Au niveau local, les <strong>mairies</strong> sont compétentes pour l'état civil (naissance, mariage), l'urbanisme, les écoles, et de nombreux services de proximité.</p>

<p>Pour un étudiant international, les interlocuteurs administratifs les plus fréquents sont : la <strong>préfecture</strong> (titre de séjour, récépissé), le <strong>bureau des étrangers</strong> de la préfecture (spécialement dédié aux questions de séjour), la <strong>CPAM</strong> (Sécurité Sociale), la <strong>CAF</strong> (allocations logement), les <strong>impôts</strong> (centre des finances publiques), et l'<strong>OFII</strong> (Office Français de l'Immigration et de l'Intégration, pour la validation du visa VLS-TS). La dématérialisation des démarches a considérablement accéléré ces dernières années avec des plateformes comme <a href="https://www.demarches-simplifiees.fr" target="_blank">démarches-simplifiées.fr</a>, <a href="https://www.service-public.fr" target="_blank">service-public.fr</a>, et <a href="https://administration-etrangers-en-france.interieur.gouv.fr" target="_blank">ANEF</a> (Administration Numérique pour les Étrangers en France) pour les démarches de séjour. Néanmoins, certaines procédures requièrent encore un déplacement physique avec prise de rendez-vous préalable. L'astuce est de prendre rendez-vous le plus tôt possible car les délais peuvent être de plusieurs semaines, voire plusieurs mois dans certaines préfectures.</p>

<h3>Les délais administratifs : comment les anticiper</h3>
<p>L'un des défis majeurs en France est la gestion des délais administratifs, souvent longs et imprévisibles. Voici les délais moyens constatés pour les principales démarches :</p>
<table>
<tr><th>Démarche</th><th>Délai moyen</th><th>Conseil</th></tr>
<tr><td>Renouvellement titre de séjour</td><td>2 à 6 mois</td><td>Déposer la demande 2 à 4 mois avant expiration</td></tr>
<tr><td>Carte Vitale</td><td>1 à 3 mois</td><td>Commander dès l'affiliation confirmée</td></tr>
<tr><td>Demande APL / CAF</td><td>1 à 2 mois</td><td>Faire la demande dès l'emménagement</td></tr>
<tr><td>Numéro de Sécu définitif</td><td>3 à 8 mois</td><td>Accepter le numéro provisoire en attendant</td></tr>
<tr><td>Échange permis de conduire</td><td>3 à 12 mois</td><td>Déposer le dossier ANEF dès l'arrivée</td></tr>
<tr><td>Avis d'imposition</td><td>Août-septembre (déclaration avril-juin)</td><td>Déclarer en ligne dès l'ouverture du service</td></tr>
</table>
<p>Un conseil essentiel : ne restez jamais sans titre de séjour valide. Si votre récépissé expire avant la délivrance de votre nouveau titre, demandez un renouvellement de récépissé à la préfecture. Le récépissé a la même valeur juridique qu'un titre de séjour pour le droit au travail et au séjour. Conservez toujours sur vous une photocopie de votre titre de séjour (ou récépissé) et gardez l'original en lieu sûr. En cas de perte ou de vol, déclarez-le immédiatement au commissariat et demandez un duplicata à la préfecture.</p>`,

  francais: `
<h3>Progresser en français grâce à l'immersion totale</h3>
<p>L'immersion linguistique est reconnue par les linguistes comme la méthode la plus efficace pour progresser rapidement dans une langue étrangère. En vivant en France, vous êtes dans une position privilégiée pour pratiquer le français au quotidien. Voici des stratégies concrètes pour maximiser votre immersion. Le <strong>tandem linguistique</strong> consiste à échanger avec un Français qui souhaite apprendre votre langue maternelle : vous passez la moitié du temps en français, l'autre moitié dans votre langue. Les plateformes <a href="https://www.tandem.net" target="_blank">Tandem</a>, <a href="https://www.conversationexchange.com" target="_blank">Conversation Exchange</a> et les groupes Facebook « Échange linguistique [votre ville] » permettent de trouver des partenaires. Les <strong>Alliances Françaises</strong> (présentes dans toutes les grandes villes) et les <strong>centres de FLE</strong> (Français Langue Étrangère) des universités proposent des cours de français à tarifs réduits pour les étudiants. Certaines universités offrent même des cours de FLE gratuits dans le cadre du <strong>programme d'accueil des étudiants internationaux</strong>.</p>

<p>Pour la <strong>compréhension orale</strong>, écoutez quotidiennement des podcasts en français : <strong>InnerFrench</strong> (niveau intermédiaire, explications claires), <strong>France Culture</strong> (niveau avancé, émissions intellectuelles), <strong>Journal en français facile</strong> de RFI (actualités en français simplifié). Regardez des films et séries français avec les sous-titres en français (pas dans votre langue !) : les plateformes comme Netflix, Canal+ et France.tv proposent un catalogue riche de contenus francophones. Pour la <strong>production écrite</strong>, tenez un journal quotidien en français, même quelques lignes. Utilisez <a href="https://www.languagetool.org" target="_blank">LanguageTool</a> ou <a href="https://bonpatron.com" target="_blank">BonPatron</a> pour corriger vos textes et comprendre vos erreurs récurrentes.</p>

<h3>Préparer le DELF et le DALF : stratégies efficaces</h3>
<p>Le <strong>DELF</strong> (Diplôme d'Études en Langue Française) et le <strong>DALF</strong> (Diplôme Approfondi de Langue Française) sont les diplômes officiels de langue française délivrés par le Ministère de l'Éducation nationale. Ils sont reconnus internationalement et valables à vie. Le DELF existe en 4 niveaux (A1, A2, B1, B2) et le DALF en 2 niveaux (C1, C2). Pour les études universitaires en France, le niveau <strong>B2 minimum</strong> est généralement exigé, et le <strong>C1</strong> est recommandé pour les masters et doctorats. Le <strong>DALF C1 ou C2</strong> dispense de tout test de langue pour l'inscription dans les universités françaises. L'inscription aux examens se fait auprès des centres agréés (liste sur <a href="https://www.france-education-international.fr/delf-dalf" target="_blank">France Éducation International</a>). Les frais d'inscription varient de 100€ (DELF A1) à 250€ (DALF C2) selon le niveau. De nombreux sites proposent des entraînements gratuits : <a href="https://savoirs.rfi.fr/apprendre-enseigner" target="_blank">RFI Savoirs</a>, <a href="https://apprendre.tv5monde.com" target="_blank">TV5Monde</a>, et <a href="https://www.francaisavecpierre.com" target="_blank">Français avec Pierre</a> sur YouTube.</p>`,

  fiscal: `
<h3>La fiscalité des étudiants étrangers en France : guide complet</h3>
<p>En tant qu'étudiant international résidant en France, vous êtes soumis à l'<strong>obligation fiscale française</strong> si vous résidez en France plus de 183 jours par an (vous êtes alors considéré comme résident fiscal français). Cela signifie que vous devez déclarer tous vos revenus mondiaux (salaires, bourses imposables, revenus du patrimoine) à l'administration fiscale française. La première déclaration de revenus se fait l'année suivant votre arrivée, entre avril et juin, sur <a href="https://www.impots.gouv.fr" target="_blank">impots.gouv.fr</a>. Si c'est votre première déclaration en France et que vous n'avez pas de numéro fiscal, rendez-vous au centre des finances publiques de votre domicile avec votre passeport et un justificatif de domicile pour obtenir votre numéro. Bonne nouvelle : la plupart des étudiants ne paient pas d'impôt sur le revenu en raison de leurs revenus modestes. Le seuil d'imposition est d'environ 10 777€ de revenu net imposable annuel (en 2024). En dessous, l'impôt est nul. De plus, les <strong>bourses d'études</strong> versées par l'État français, les collectivités territoriales ou les établissements publics sont exonérées d'impôt. Les <strong>indemnités de stage</strong> obligatoire sont exonérées dans la limite du SMIC annuel. Les <strong>salaires des jobs étudiants</strong> sont exonérés dans la limite de 3 fois le SMIC mensuel (environ 4 936€ en 2024) si vous avez moins de 26 ans et que vous êtes étudiant.</p>

<p>L'<strong>avis d'imposition</strong> est un document crucial en France. Même si vous ne payez pas d'impôt (avis de non-imposition), ce document sert de justificatif de revenus pour de nombreuses démarches : demande de logement social, calcul des allocations CAF, inscription au tarif social des transports, accès à la Complémentaire Santé Solidaire, etc. Conservez tous vos avis d'imposition pendant au moins 3 ans. En cas d'erreur dans votre déclaration, vous pouvez la corriger en ligne sur impots.gouv.fr jusqu'en décembre de l'année en cours. Si l'erreur est en votre faveur (trop-perçu), le trésor public vous rembourse par virement sous quelques semaines.</p>`,

  aides: `
<h3>Panorama complet des aides financières pour étudiants internationaux</h3>
<p>La France offre un éventail d'aides financières particulièrement large pour les étudiants, y compris les étudiants internationaux. Voici un panorama complet des aides disponibles :</p>
<ul>
<li><strong>Bourses sur critères sociaux du CROUS</strong> : réservées principalement aux étudiants européens et aux étudiants réfugiés ou résidents en France depuis au moins 2 ans avec un parent travaillant en France. Montant : de 1 084€ à 6 335€ par an selon l'échelon (0bis à 7). Demande via le <a href="https://www.messervices.etudiant.gouv.fr" target="_blank">Dossier Social Étudiant (DSE)</a> entre le 15 janvier et le 15 mai.</li>
<li><strong>Aides d'urgence du CROUS (ASAP)</strong> : aide ponctuelle ou mensuelle pour les étudiants en situation de précarité (y compris étrangers), sur décision du directeur du CROUS. Demande auprès de l'assistant social du CROUS. Montant ponctuel : jusqu'à 1 707€. Aide mensuelle : jusqu'à 6 335€/an.</li>
<li><strong>Aide au mérite</strong> : complément de 900€/an pour les étudiants boursiers ayant obtenu la mention Très Bien au baccalauréat.</li>
<li><strong>Aide à la mobilité Master</strong> : 1 000€ pour les étudiants boursiers changeant de région pour un Master. Demande sur <a href="https://www.messervices.etudiant.gouv.fr" target="_blank">messervices.etudiant.gouv.fr</a>.</li>
<li><strong>Bourses Erasmus+</strong> : pour les étudiants en échange européen, 250-350€/mois selon le pays d'accueil.</li>
<li><strong>Bourses du gouvernement français (BGF)</strong> : pour les étudiants internationaux sélectionnés par Campus France, couvrant frais de scolarité, allocation mensuelle (700-1 050€) et couverture sociale.</li>
<li><strong>Aide personnalisée au logement (APL)</strong> : pour tous les étudiants quel que soit leur nationalité, calculée selon les revenus et le loyer. Demande sur <a href="https://www.caf.fr" target="_blank">caf.fr</a>.</li>
<li><strong>Fonds de solidarité et d'aide aux initiatives étudiantes (FSDIE)</strong> : aide ponctuelle gérée par chaque université pour les étudiants en difficulté. Renseignez-vous auprès du service de la vie étudiante de votre établissement.</li>
</ul>

<p>Pour identifier toutes les aides auxquelles vous avez droit, utilisez le simulateur gratuit <a href="https://www.1jeune1solution.gouv.fr/mes-aides" target="_blank">1jeune1solution.gouv.fr</a> qui recense plus de 500 aides locales et nationales. Les <a href="https://www.etudiant.gouv.fr" target="_blank">CROUS</a> proposent également des services de restauration à tarif social (repas à 3,30€, ou 1€ pour les étudiants boursiers ou en précarité) dans leurs restaurants universitaires.</p>`,

  universite: `
<h3>L'organisation de l'enseignement supérieur français</h3>
<p>Le système d'enseignement supérieur français est structuré selon le schéma européen <strong>LMD (Licence-Master-Doctorat)</strong> : la Licence se prépare en 3 ans (180 crédits ECTS), le Master en 2 ans (120 ECTS supplémentaires), et le Doctorat en 3 ans minimum. L'enseignement s'organise en <strong>CM (Cours Magistraux)</strong>, dispensés en amphithéâtre par un professeur devant l'ensemble de la promotion (souvent 100-500 étudiants), et en <strong>TD (Travaux Dirigés)</strong> et <strong>TP (Travaux Pratiques)</strong>, en groupes restreints de 20-40 étudiants pour approfondir les notions vues en CM. La présence en TD/TP est obligatoire (contrôle d'assiduité), tandis que celle en CM est généralement libre mais vivement recommandée.</p>

<p>Le système de notation français est sur 20 points, avec 10/20 comme moyenne suffisante pour valider. Le système de compensation permet qu'une note inférieure à la moyenne dans une matière soit compensée par une note supérieure dans une autre, si la moyenne générale de l'UE (Unité d'Enseignement) ou du semestre atteint 10/20. Les examens prennent deux formes : le <strong>contrôle continu</strong> (notes régulières pendant le semestre : devoirs, exposés, partiels intermédiaires) et le <strong>contrôle terminal</strong> (examen final en fin de semestre). La plupart des formations combinent les deux. En cas d'échec, des <strong>sessions de rattrapage</strong> sont organisées (généralement en juin pour le premier semestre et en septembre pour le second). Les étudiants qui ne valident pas leur année peuvent redoubler (droit au redoublement une fois par cycle dans la plupart des universités).</p>`,

  securite: `
<h3>La sécurité au quotidien en France : prévention et réflexes</h3>
<p>La France est globalement un pays sûr, mais comme dans tout pays, il existe des risques qu'il est bon de connaître, surtout dans les grandes agglomérations. Les <strong>pickpockets</strong> sont présents dans les zones touristiques très fréquentées (Tour Eiffel, Champs-Élysées, métro parisien, gares) et ciblent souvent les touristes et étudiants étrangers. Précautions de base : portez votre sac devant vous dans les transports en commun, ne laissez jamais votre téléphone sur la table d'un café, évitez de montrer des signes ostentatoires de richesse (bijoux, montres, téléphone dernier modèle). En cas de vol, déposez une plainte au commissariat ou en ligne sur <a href="https://www.pre-plainte-en-ligne.gouv.fr" target="_blank">pre-plainte-en-ligne.gouv.fr</a>. Le récépissé de plainte est nécessaire pour votre assurance et pour faire opposition sur vos cartes bancaires.</p>

<p>Le système <strong>FR-Alert</strong>, déployé depuis 2022, envoie des notifications sur votre téléphone mobile en cas de danger imminent dans votre zone géographique (attentat, catastrophe naturelle, accident industriel). Aucune inscription n'est nécessaire : toute personne avec un téléphone compatible reçoit automatiquement les alertes. En cas d'attentat, le réflexe est « s'échapper, se cacher, alerter » (appeler le 17 ou le 112). Pour votre <strong>sécurité numérique</strong>, soyez vigilant face aux arnaques en ligne : les faux emails de la CAF, de la Sécurité Sociale, ou de votre banque (phishing) sont fréquents. Ne cliquez jamais sur un lien dans un email vous demandant de « vérifier vos coordonnées » ou de « régulariser un paiement » – connectez-vous directement sur le site officiel via votre navigateur. Le site <a href="https://www.cybermalveillance.gouv.fr" target="_blank">cybermalveillance.gouv.fr</a> référence les arnaques en cours et donne des conseils de prévention.</p>`,

  culture: `
<h3>Comprendre et s'adapter à la culture française</h3>
<p>La culture française possède des codes sociaux spécifiques qui peuvent surprendre les étudiants internationaux. Comprendre ces codes est essentiel pour s'intégrer harmonieusement. La <strong>ponctualité</strong> est très valorisée dans le cadre professionnel et universitaire (arriver en retard à un cours ou un rendez-vous est considéré comme impoli), mais socialement, il est courant et accepté d'arriver avec 15-20 minutes de retard à un dîner chez des amis (le fameux « quart d'heure de politesse »). La <strong>conversation à table</strong> est un art en France : les Français aiment débattre, argumenter et confronter les idées. Ne prenez pas un désaccord comme une attaque personnelle – c'est souvent un signe d'intérêt et de respect intellectuel. Les sujets de conversation appréciés incluent la politique, la culture, la gastronomie et les voyages. Les sujets à éviter en début de relation incluent le salaire, la religion et les questions trop personnelles.</p>

<p>Les <strong>repas français</strong> suivent une structure précise : entrée, plat principal, fromage, dessert. À table, ne commencez pas à manger avant que l'hôte ou la personne la plus âgée ne commence. Posez les deux mains sur la table (pas sur les genoux comme dans la culture anglo-saxonne). Le pain se pose directement sur la nappe ou sur une assiette à pain, jamais retourné (superstition française). Pour <strong>se faire des amis</strong> en France, rejoignez des associations étudiantes (BDE, associations sportives, clubs de langue), participez aux événements organisés par votre université (soirées d'intégration, sorties culturelles), et fréquentez les cafés et terrasses – lieux emblématiques de la vie sociale française. Les Français peuvent sembler réservés au premier abord, mais une fois la « bulle » percée, ils deviennent des amis fidèles et généreux. Les applications comme <a href="https://www.meetup.com/fr-FR/" target="_blank">Meetup</a> et <a href="https://www.internations.org" target="_blank">InterNations</a> organisent des événements sociaux spécifiquement pour les expatriés et étudiants internationaux dans toutes les grandes villes françaises.</p>`,

  pratique: `
<h3>S'organiser au quotidien en France : astuces pratiques</h3>
<p>La vie quotidienne en France a ses propres rythmes et usages qu'il est utile de connaître pour s'organiser efficacement. Les <strong>horaires d'ouverture des commerces</strong> varient selon les villes et les quartiers : en général, les magasins ouvrent de 9h-10h à 19h-20h du lundi au samedi, et restent fermés le dimanche (sauf exceptions dans les zones touristiques et les supermarchés). En France, le <strong>dimanche est traditionnellement un jour de repos</strong>, et de nombreux services sont fermés. Prévoyez vos courses en conséquence. Les supermarchés (<a href="https://www.carrefour.fr" target="_blank">Carrefour</a>, <a href="https://www.leclerc.fr" target="_blank">E.Leclerc</a>, Auchan, Intermarché) ferment généralement entre 20h et 22h en semaine. Les hard-discounters (Lidl, Aldi, Action) sont les options les plus économiques pour les courses alimentaires de base.</p>

<p>Pour les <strong>achats en ligne</strong>, Amazon.fr domine le marché mais il existe des alternatives françaises : <a href="https://www.cdiscount.com" target="_blank">Cdiscount</a> (électronique, maison), <a href="https://www.fnac.com" target="_blank">Fnac</a> (livres, culture, tech), <a href="https://www.vinted.fr" target="_blank">Vinted</a> (vêtements d'occasion), <a href="https://www.leboncoin.fr" target="_blank">Leboncoin</a> (tout d'occasion). Les <strong>pharmacies</strong> (croix verte) sont le point de passage obligé pour les médicaments, même ceux sans ordonnance comme le paracétamol. Les <strong>bureaux de tabac</strong> vendent les timbres postaux, les timbres fiscaux, les recharges téléphoniques, et servent souvent de relais colis. La <strong>Poste</strong> reste le service postal de référence : un timbre lettre verte (distribution sous 3 jours) coûte 1,16€ en 2024. Pour les colis, les <strong>points relais</strong> (Mondial Relay, Relais Colis) sont souvent moins chers et plus pratiques que la livraison à domicile.</p>

<p>Les <strong>jours fériés français</strong> sont au nombre de 11 par an : 1er janvier, lundi de Pâques, 1er mai, 8 mai, Ascension, lundi de Pentecôte, 14 juillet, 15 août, 1er novembre, 11 novembre, 25 décembre. Lorsqu'un jour férié tombe un mardi ou un jeudi, les Français pratiquent souvent le <strong>« pont »</strong> (prendre le lundi ou le vendredi comme jour de congé pour avoir un week-end prolongé). Les cours à l'université peuvent être supprimés lors des ponts, renseignez-vous auprès de votre scolarité.</p>`,
};

  const extra = extraBlocks[topic] || extraBlocks.pratique;
  return extra;
}

async function main() {
  console.log('Fetching all lessons...');
  const allLessons = await fetchAll();
  console.log(`Total lessons: ${allLessons.length}`);

  // Get course titles
  const coursesRes = await fetch(`${SUPABASE_URL}/rest/v1/courses?select=id,title`, { headers: H });
  const courses = await coursesRes.json();
  const courseMap = {};
  courses.forEach(c => { courseMap[c.id] = c.title; });

  // Filter under 4000
  const under = allLessons.filter(l => l.content.split(' ').length < 4000);
  under.sort((a, b) => a.content.split(' ').length - b.content.split(' ').length);
  console.log(`${under.length} lessons still under 4000 words`);
  console.log(`Shortest: ${under[0]?.content.split(' ').length} words`);

  let success = 0, fail = 0;
  for (const l of under) {
    const courseTitle = courseMap[l.course_id] || '';
    const extra = generateExtra(l.title, courseTitle);
    const enriched = l.content + '\n\n' + extra;
    const newWc = enriched.split(' ').length;

    if (newWc > l.content.split(' ').length + 200) {
      const status = await update(l.id, enriched);
      if (status === 204) {
        success++;
        if (success % 50 === 0) console.log(`... ${success} enriched`);
      } else {
        fail++;
        console.log(`FAIL: ${l.title} (${status})`);
      }
    }
  }

  console.log(`\n=== PASS 2 DONE ===`);
  console.log(`Enriched: ${success} | Failed: ${fail}`);

  // Quick stats
  const all2 = await fetchAll();
  const above = all2.filter(l => l.content.split(' ').length >= 4000).length;
  const below = all2.filter(l => l.content.split(' ').length < 4000).length;
  console.log(`Now: ${above} above 4000 words, ${below} below`);
}

main().catch(console.error);
