export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    // Parser le body si nécessaire
    let body = req.body;
    
    if (typeof body === 'string') {
      try {
        body = JSON.parse(body);
      } catch (e) {
        console.error('[Gemini] Body parse error:', e.message);
        return res.status(400).json({ error: 'Invalid JSON in request body' });
      }
    }
    
    if (!body || (typeof body === 'object' && Object.keys(body).length === 0)) {
      body = req.body || {};
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('[Gemini] GEMINI_API_KEY not configured');
      return res.status(500).json({ 
        error: 'GEMINI_API_KEY not configured on server',
        message: 'Please configure GEMINI_API_KEY in Vercel project settings → Environment Variables'
      });
    }

    const prompt = body.prompt;
    if (!prompt) {
      console.error('[Gemini] Missing prompt');
      return res.status(400).json({ error: 'Missing prompt' });
    }

    // Utiliser UNIQUEMENT gemini-2.5-flash
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
    
    const payload = {
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048,
      },
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
      ]
    };

    console.log('[Gemini] Request to gemini-2.5-flash, prompt length:', prompt.length);
    
    const upstream = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    const rawText = await upstream.text();
    let json;
    try {
      json = JSON.parse(rawText);
    } catch (parseErr) {
      console.error('[Gemini] JSON parse error. Status:', upstream.status, 'Raw:', rawText.substring(0, 500));
      return res.status(500).json({ 
        error: 'Invalid JSON from Gemini', 
        status: upstream.status, 
        detail: rawText.substring(0, 200) 
      });
    }

    if (!upstream.ok) {
      console.error('[Gemini] API error:', upstream.status, JSON.stringify(json).substring(0, 500));
      const errorMessage = json.error?.message || json.error || 'Gemini API error';
      
      if (upstream.status === 401 || upstream.status === 403) {
        return res.status(500).json({ 
          error: 'Invalid API key',
          message: 'Please check your GEMINI_API_KEY in Vercel environment variables'
        });
      }
      if (upstream.status === 429) {
        return res.status(500).json({ 
          error: 'Rate limit exceeded',
          message: 'Gemini API quota exceeded. Please try again later.'
        });
      }
      if (upstream.status === 404) {
        return res.status(500).json({ 
          error: 'Model not found',
          message: `gemini-2.5-flash is not available. Error: ${errorMessage}`
        });
      }
      
      return res.status(500).json({ 
        error: errorMessage,
        status: upstream.status
      });
    }

    const content = json.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!content) {
      console.error('[Gemini] No content in response:', JSON.stringify(json).substring(0, 300));
      return res.status(500).json({ error: 'No content generated by Gemini' });
    }
    
    console.log('[Gemini] Success! Content length:', content.length);
    return res.status(200).json({ content });
  } catch (err) {
    console.error('[Gemini] Server error:', err.message);
    console.error('[Gemini] Stack:', err.stack);
    return res.status(500).json({ 
      error: err.message || 'Unknown server error',
      message: 'An error occurred while processing your request. Please check the server logs for more details.'
    });
  }
}
