module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    // Parser le body si nécessaire
    let body = req.body;
    if (!body || typeof body === 'string') {
      try {
        body = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {});
      } catch (e) {
        console.error('[Gemini] Body parse error:', e.message);
        body = {};
      }
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('[Gemini] GEMINI_API_KEY not configured');
      return res.status(500).json({ error: 'GEMINI_API_KEY not configured on server' });
    }

    const prompt = body.prompt;
    if (!prompt) {
      console.error('[Gemini] Missing prompt in request');
      return res.status(400).json({ error: 'Missing prompt' });
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
    const payload = {
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048,
      },
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
      ]
    };

    const upstream = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    const rawText = await upstream.text();
    let json;
    try {
      json = JSON.parse(rawText);
    } catch (parseErr) {
      console.error('[Gemini] JSON parse error. Status:', upstream.status, 'Raw:', rawText.substring(0, 500));
      return res.status(500).json({ error: 'Invalid JSON from Gemini', status: upstream.status, detail: rawText.substring(0, 200) });
    }

    if (!upstream.ok) {
      console.error('[Gemini] API error:', upstream.status, json);
      return res.status(upstream.status).json({ error: json.error?.message || 'Gemini API error' });
    }

    const content = json.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!content) {
      console.error('[Gemini] No content in response:', JSON.stringify(json).substring(0, 300));
      return res.status(500).json({ error: 'No content generated by Gemini' });
    }
    
    return res.status(200).json({ content });
  } catch (err) {
    console.error('[Gemini] Server error:', err.message, err.stack);
    return res.status(500).json({ error: err.message || 'Server error' });
  }
};
